bins/src/bin/datadog-static-analyzer-server.rs
server/src/analysis.rs
server/src/constants.rs
server/src/lib.rs
server/src/model.rs
server/src/model/analysis_request.rs
server/src/model/analysis_response.rs
server/src/model/tree_sitter_tree_request.rs
server/src/model/tree_sitter_tree_response.rs
server/src/request.rs
server/src/tree_sitter_tree.rs

We need to expose an API endpoint to print the AST in JSON
Add the `/get-treesitter-ast` API that returns the root node of the code passed as parameter.
We also addressed the log output but that was caused by naming conventions issues (using `camelCase` instead of `snake_case`).

Add server AST endpoint

---

kernel/src/model/analysis.rs
server/src/model.rs
server/src/model/tree_sitter_tree_node.rs
server/src/model/tree_sitter_tree_response.rs
server/src/tree_sitter_tree.rs

The server API uses `camelCase` for all attributes when it should returns `snake_case`. The serde serialization for the node is using `camelCase`, which is what we expect in rules for JavaScript code. We need to have the conversion in the server to use `snake_case`.

use_snake_case_for_server_api

---

.github/workflows/release.yml

We forgot to replace `core` by `kernel` in the GitHub release action.
Fix the typo

Fix release pipeline for the CLI

---

DEVELOPMENT.md

Changed the docs because they were still mentioning a script that is no longer needed.

docs(build): fix the tree-sitter installation docs

---

.github/workflows/rust.yaml
bins/src/bin/datadog-static-analyzer-test-ruleset.rs
bins/src/bin/datadog-static-analyzer.rs
kernel/src/analysis/javascript.rs
kernel/src/analysis/tree_sitter.rs

We had rules that randomly timed'out and did not give any results. It makes the execution of the tool unpredictable and our pipelines failed (see example [here](https://github.com/DataDog/datadog-static-analyzer/actions/runs/5490472654/jobs/10005956655) or [here](https://github.com/DataDog/datadog-static-analyzer/actions/runs/5490529721/jobs/10006087565)).
The problem we have is that the function was executing too fast. So the main thread did not had the opportunity to wait for the thread termination. Instead, it was waiting for a termination that already happened.
The main issue is that before we do `cvar.wait_timeout` in the main thread, the child thread must have the opportunity to execute `cvar.notify_one();`. If the thread execute `cvar.notify_one();` before the main thread …

Fix rule timeout

---

.github/workflows/release.yml

There was a copy paste typo from the original action. Modified the text to describe current status of the action step.

chore(typo): fix typo in release action

---

Cargo.toml
LICENSE-3rdparty.csv
bins/Cargo.toml
cli/Cargo.toml
kernel/Cargo.toml
kernel/src/analysis/javascript.rs
server/Cargo.toml
server/src/model/analysis_request.rs
server/src/model/analysis_response.rs
server/src/model/tree_sitter_tree_node.rs
server/src/model/tree_sitter_tree_request.rs
server/src/model/tree_sitter_tree_response.rs

1. The repo has different crates that share some dependencies. Now, those dependencies are declared in each Cargo.toml, along with their versions. This can make difficult to upgrade the version of the dependencies in order to keep all of them in sync.
1. We have a dependency on `serde_derive`.
1. The solution is to use [Cargo Workspace Depencencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table).
1. Use serde's `derive` feature.
Nor 1 or 2 are inherently a problem. This are suggestions to basically reduce the maintainability cost (1) and reduce the number of third party dependencies (2)
Other projects using similar approach:
- [Cargo](https://github.com/rust-lang/cargo/blob/master/Cargo.toml#L13)
- [Rust …

feat(workspace): use workspace dependencies

---

bins/src/bin/datadog-export-rulesets.rs
bins/src/bin/datadog-static-analyzer.rs
kernel/src/constants.rs
kernel/src/utils.rs

1. There are two different places in the the `kernel` crate that were exposing a VERSION const:
1. [utils.rs](https://github.com/robertohuertasm/datadog-static-analyzer/blob/ffce75f6a1c387b7a0e6f27089eb4463b3febb37/kernel/src/utils.rs#L4)
2. [constants.rs](https://github.com/robertohuertasm/datadog-static-analyzer/blob/ffce75f6a1c387b7a0e6f27089eb4463b3febb37/kernel/src/constants.rs#L1)
1. Some crates don't expose the version, so it may be difficult to determine if we have the latest build.
1. Remove the code in [utils](https://github.com/robertohuertasm/datadog-static-analyzer/blob/ffce75f6a1c387b7a0e6f27089eb4463b3febb37/kernel/src/utils.rs#L4) as it seems that it's not being used at all.
2. Add a `--version` flag for some CLIs so that consumers can understand which version are they …

feat(version): add version information to some binaries

---

DEVELOPMENT.md
LICENSE-3rdparty.csv
bins/src/bin/datadog-static-analyzer-test-ruleset.rs
bins/src/bin/datadog-static-analyzer.rs
cli/Cargo.toml
cli/src/lib.rs
cli/src/sarif.rs
cli/src/sarif/sarif-schema-2.1.0.json
cli/src/sarif/sarif_utils.rs

1. We want to make sure that our SARIF output is compliant with the SARIF standard.
2. We want to also surface the correct `enum` value for level
1. Add test with [valico](https://github.com/s-panferov/valico) to validate that the output from the analyzer is compliant with the SARIF schema.
2. Fix the enum value being surface and map `Notice` to `note`

Add SARIF validation tests + fix level

---

.github/workflows/release.yml

As I was testing the server binary to see how we could work with it in our extension, I realized that the Windows binary was not sending the version.
Not sure if this is going to solve it as it seems that the substitution is taking place, given that when I do a request to the `version` endpoint I don't get `development` but an empty string.
In any case, it's a good practice to use the `bash` shell so typical Unix commands can get executed in Windows. See [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell) for more information. 
I'm submitting this under the assumption that `sed` will work as expected when executed in a bash shell.
Screenshot of the server not returning anything:

fix(windows): use shell in actions

---

bins/src/bin/datadog-static-analyzer.rs
cli/src/model/cli_configuration.rs
kernel/src/model/common.rs

When executing our analyzer in container, it gets the number of cpus incorrectly. We need to bring a way to control the parallelism of the analyzer.
Add a `-cpus` option that lets the user define the number of CPU on the host. If the program is executed on a host where the number of not correctly detected, it will let them override the default value.
We refactored the code to avoid having too many configuration variable. We put all the cli configuration in a common data structure `CliConfiguration`.

add --cpus option to control parallelism

---

.gitlab-ci.yml
bins/src/bin/datadog-static-analyzer-server.rs

We want to support serving static files for the server. We did it before but we need to specify the path for each file. As we will serve all the WASM files, we want to just specify one directory that will contain all the static files.
Add a new flag `-s` or `--static` that provides a single directory that contains all static files to serve. If a static file is requested and is in the directory, we return it.
For extra safety, we ensure that the file does not contain `..` or start with `.` to prevent any malicious users to walk through the file hierarchy.

add support for static files

---

Cargo.toml
LICENSE-3rdparty.csv
bins/Cargo.toml
bins/src/bin/datadog-static-analyzer.rs
kernel/src/analysis/javascript.rs

We want to solve two problems:
1. Showing more information to the user about how many violations have been found in how many files in how long
2. Troubleshooting the rules and see what rules take most time
For (1), we surface a message like the following once we execute the tool.
```
Found 314 violations in 311 files within 7 secs
```
For (2), we add an option (`-x`) that shows the cumulative time spent in a rule. It tells us exactly what rule are taking a lot of time and help us prioritize what rule to optimize.
```
Rule execution time
-------------------
rule "python-code-style/max-function-lines" execution time 1064 ms
rule "python-design/function-too-long" execution time 1052 ms
Rule timed out
--------------
No rule timed out
```
We fixed a bug in `javascript.rs` to report the …

add more information about the analysis

---

cli/src/sarif/sarif_utils.rs
kernel/src/model/rule.rs

We want to export the rule category in the SARIF report.
Export the category. Put the category in the report as a property using a `propertyBag`. The property is under the tag `DATADOG_CATEGORY`. See the example below.
```
{
"fixes": [
{
"artifactChanges": [
{
"artifactLocation": {
"uri": "yaml_load.py"
},
"replacements": [
{
"deletedRegion": {
"endColumn": 10,
"endLine": 3,
"startColumn": 6,
"startLine": 3
},
"insertedContent": {
"text": "safe_load"
}
}
]
}
],
"description": {
"text": "use safe_load"
}
}
],
"level": "warning",
"locations": [
{
"physicalLocation": {
"artifactLocation": {
"uri": "yaml_load.py"
},
"region": {
"endColumn": 10,
"endLine": 3,
"startColumn": 6,
"startLine": 3
}
}
}
],
"message": {
"text": "prefer using safe_load to avoid arbitrary code execution"
}, …
```

Export category from sarif report

---

kernel/src/analysis/analyze.rs
kernel/src/analysis/tree_sitter.rs

We want to be able to capture unnamed nodes from the tree-sitter queries.
Our solution is to capture unnamed node in the initial called to `map_node`. Doing so allows us to capture unnamed node. For all the children of the node captures, we only capture named nodes.
Added a test from the JIRA ticket to make sure this is correctly captured/handled.

Support unnamed nodes capture

---

bins/src/bin/datadog-static-analyzer-server.rs
kernel/src/model/common.rs

We want to expose the languages supported by the analyzer. The server must return the list of supported languages.
Adding the endpoint that returns all the languages available using the list from the `kernel.`
```
curl http://localhost:8000/languages
["CSHARP","DOCKERFILE","GO","JAVA","JAVASCRIPT","JSON","PYTHON","RUST","TYPESCRIPT"]%
```

add endpoint to return languages

---

bins/src/bin/datadog-static-analyzer.rs

We want to enable debug via environment variables. This way, in a CI/CD pipeline, customers can simply enable a environment variable instead of modifying how they invoke a command.
Check the environment variable is set when we enable debug mode.

enable debug via environment variables

---

.github/workflows/release.yml
Cargo.toml
bins/Cargo.toml
bins/src/bin/datadog-static-analyzer-server.rs
bins/src/bin/datadog-static-analyzer.rs
cli/Cargo.toml
kernel/Cargo.toml
kernel/src/constants.rs
server/Cargo.toml
versions.json

We want to be able to track the number of versions that are offered along with the major and minor versions.
1. First, we need to make sure we have a consistent versioning mechanism across the software. We declare one version in the `Cargo.toml` at the root directory and use this version across the workspace. Each module refers to the workspace version using `version.workspace = true`. See [this documentation](https://doc.rust-lang.org/cargo/reference/workspaces.html) for more information
2. We introduce a file `versions.json` that we keep to track all our versions. This file will be available at `https://github.com/DataDog/datadog-static-analyzer/releases/latest/download/versions.json`
3. We upload this file when we release a new version using a new GitHub Action
We updated our release …

Add file to track versions

---

bins/src/bin/datadog-static-analyzer-server.rs

We want to have a separate `/version` and `/revision` endpoint. For the `/revision`, it shows us the exact Git version running. The `/version` will be useful for the IDE integration to distinguish exactly the version running and if there is a need to upgrade
Have two endpoints:
- `/version` used to show the cargo version (e.g. `0.0.5`)
- `/revision` that shows the Git SHA of the code running
```
curl http://127.0.0.1:8000/version …
```

separate /version and /revision

---

Cargo.toml
LICENSE-3rdparty.csv
bins/src/bin/datadog-static-analyzer.rs
kernel/Cargo.toml
kernel/src/model/rule.rs
kernel/src/utils.rs
server/Cargo.toml
server/src/constants.rs
server/src/request.rs

We want to check the checksum of the rules to make sure there is no issue with the rules, either from a consistency or security issues. 
1. For each server request, we check the checksum passed. If the checksum is not correct, we return an error
2. For the CLI, we check the checksum of each rule. If one checksum is incorrect, we panic and exit the program
We added a `-b` option (disabled by default) to bypass the checksum check if needed.
```
[julien.delange@kaneda]/Users/julien.delange/git/datadog-static-analyzer#cargo run --bin datadog-static-analyzer -- --directory /Users/julien.delange/git/rosie-tests -o plop.json --debug yes
Compiling datadog-static-analyzer v0.0.5 (/Users/julien.delange/git/datadog-static-analyzer/bins)
Finished dev [unoptimized + debuginfo] target(s) in 1.53s …
```

Check rule checksum

---

bins/src/bin/datadog-static-analyzer.rs

Clarify the help information.
```
Usage: target/debug/datadog-static-analyzer FILE [options]
Options:
-i, --directory /path/to/code/to/analyze
directory to scan (valid existing directory)
-r, --rules /path/to/rules.json
rules to use (json file)
-d, --debug yes/no  use debug mode
-f, --format json/sarif/csv
format of the output file
-o, --output output.json
output file name
-c, --cpus --cpus 5 set the number of CPU, use to parallelize (default is
the number of cores on the platform)
-p, --ignore-path **/test*.py (multiple values possible)
path to ignore
-h, --help          print this help
-v, --version       shows the version
-b, --bypass-checksum
bypass checksum verification
-x, --performance-statistics
enable performance statistics
```

add more information in the help

---

server/src/model/tree_sitter_tree_node.rs
server/src/tree_sitter_tree.rs

It's not really a problem, but I thought I would introduce this change to provide a more idiomatic way of dealing with type transformations.
The solution is avoid using a custom function for type transformation and implement the `From` trait.
See [From and Into](https://doc.rust-lang.org/rust-by-example/conversion/from_into.html) or the [From trait docs](https://doc.rust-lang.org/std/convert/trait.From.html) for more info.

chore(from): use the From trait for ServerTreeSitterNode

---

.github/workflows/integration-tests.yaml
LICENSE-3rdparty.csv
bins/src/bin/datadog-static-analyzer.rs
cli/Cargo.toml
cli/src/sarif/sarif_utils.rs
misc/integration-test.sh

We want to add the SHA related to a violation in the SARIF report.
1. We are adding a `-g` option
2. When the `-g` option is specific, we add the `SHA` for a violation by running `git blame` on it
This has been tested against the repository https://github.com/juli1/rosie-tests (see the section on integration tests below).
Since it's hard to have unit tests for such a feature, we added a script for doing integration tests. This integration test script is found in `misc/integration-test.sh`. It is added in our GitHub actions.
This scripts
- Get the repository https://github.com/juli1/rosie-tests
- Run the new stella with the `-g` option
- Check that the SHA and the CATEGORY tags are in the report

add SHA to SARIF report

---

bins/src/bin/datadog-static-analyzer.rs
cli/resources/test/gitignore/test1
cli/src/file_utils.rs
cli/src/model/cli_configuration.rs
cli/src/model/config_file.rs

1. We need to add support to ignore directories from `.gitignore`
2. This mechanism can be disabled using the directive `ignore_gitignore` in the `static-analysis.datadog.yml` file
1. Ignore all directories from the `.gitignore` file
2. Add an attribute `ignore-gitignore` in the `static-analysis.datadog.yml` to disable the logic
3. print all ignored paths in the tool configuration section
We skipped all entries with `!` in the `.gitignore` file. The reason is that it filters all files when using it. For example, on [dd-trace-py](https://github.com/DataDog/dd-trace-py), the entry `!.env` skipped all files. We are therefore ignoring such entries for now.

add support for gitignore

---

cli/src/datadog_utils.rs
kernel/Cargo.toml
kernel/src/analysis/javascript.rs

Upgrade deno + handle unauthenticated requests
1. Make the code compliant with the latest version of deno
2. If the `DD_APP_KEY` or `DD_API_KEY` variables are not defined, do not send any key and send an authenticated request to datadog.

upgrade deno + handle unauthenticated requests

---

.github/workflows/versions-check.yaml

We want to make sure that the `versions.json` file is always correct. An invalid version would cause issue with the IDE integration team. We want to ensure we avoid this.
Enable a check at each push and ensure the file can be at least parsed.

Add check for the versions.json correctness

---

bins/src/bin/datadog-static-analyzer.rs
cli/src/sarif/sarif_utils.rs

The analyzer does not find the blame information sometimes. For this reason, we cannot crash when the blame information is not found. We should instead print a message when in `debug` mode.
Adapt the analyzer to prevent it to crash if the blame information cannot be found.

Do not crash when we cannot get blame information

---

.github/workflows/release.yml
Cargo.toml
versions.json

1. We want to avoid having an array in `versions.json` and have a dictionary 
2. Have another release to upload the server on the release
1. Define the version in a dictionary
3. Add the server artifact in `versions.json`
4. Release the cli in `datadog-static-analyzer` (what the CI/CD consumes today) and the server in `datadog-static-analyzer-server`

Update server and cli separately

---

bins/src/bin/datadog-static-analyzer-server.rs

Don't rely on the full HTTP server being ran to determine the version
Copy the version flag and output format from the main CLI
```
➜  datadog-static-analyzer git:(addServerVersionFlag) cargo run --bin datadog-static-analyzer-server -- -h
warning: tree-sitter-go/src/parser.c:242:18: warning: null character(s) preserved in string literal [-Wnull-character]
warning:   [anon_sym_] = "<U+0000>",
warning:                  ^
warning: 1 warning generated.
Finished dev [unoptimized + debuginfo] target(s) in 0.21s
Running `target/debug/datadog-static-analyzer-server -h`
Usage: target/debug/datadog-static-analyzer-server [options]
Options:
-s, --static /path/to/directory
directory for static files
-p, --port 8000     port to run the server on
-h, --help          print this help
-v, --version …
```

Adds in a -v / --version for the server CLI

---

cli/src/file_utils.rs

We previously only filtered by glob and did not filter by prefix. We should filter also by prefix.
If a user has a `.gitignore` with the following content:
```
node_modules
```
We should then ignore all path that starts with `node_modules`.
Filter for all prefixes in the ignore paths.

Filter files by prefix

---

LICENSE-3rdparty.csv
bins/Cargo.toml
bins/src/bin/datadog-static-analyzer.rs
cli/src/file_utils.rs

We want to add a progress bar in the command line.
Use the [indicatif](https://docs.rs/indicatif/latest/indicatif/) library to show the progress. We do not use colors as it could sometimes not render well in logs.
- Fixed a bug to make sure we report issues all all languages, not only the latest one.
- Also enable the progress bar only when not in debug mode. Otherwise, it puts too much information on the terminal.

Add progress bar in the CLI

---

Cargo.toml
bins/src/bin/datadog-static-analyzer-server.rs
cli/src/sarif/sarif_utils.rs

Not sure why we are exiting with 1 in some valid use cases. I found this while integrating the server into VS Code. The exit code made the commands receive an error.
Changed exit to 0 to avoid node errors when spawing the process.
For what I can see, there are other places in the codebase that could potentially run into the same kind of issues. Nonetheless, I've focused this PR into the IDE related codebase.
This PR is built on top of #77 but due to the fact that I must have a fork in order to contribute I cannot seem to make chained PRs.
So please, review #77 first, and merge it before this one. I'll rebase if needed.
IDE-1596

fix(exit): correct exit codes for non-error ops

---

Cargo.toml
cli/src/sarif/sarif_utils.rs

There are some issues affecting potential contributors working with the latest stable version. 
1. The workspace resolver must be explicitly set. 
2. There are new clippy warnings that would block the pipeline.
Note: all this came up while I was trying to prepare another PR for the IDE integration. I wasn't able to push because of the local tests. I'll prepare right away after this one, and will make it dependant on it.
1. I set the workspace resolver to 2.
2. I changed the usage of `Arc` for `Rc`.  It seems that `Arc` was not needed as far as I could see given that we're not using threads or any sort of parallellism. The main complain from Clippy was that the wrapped type (`Repository`) was not `Send` and `Sync`.

fix(stable): tests not passing

---

bins/src/bin/datadog-export-rulesets.rs
bins/src/bin/datadog-static-analyzer-test-ruleset.rs
bins/src/bin/datadog-static-analyzer.rs
cli/src/datadog_utils.rs
cli/src/file_utils.rs
cli/src/model/cli_configuration.rs

Since we will be using staging to write rules, we need to be able to easily test the rules in staging.
We are introduced the flag `--staging` that will force the analyzer and other binaries to use the staging endpoint.

Add --staging flag to fetch rules from staging

---

cli/src/file_utils.rs

Support docker and Dockerfile
Add three ways to filter file
- by extensions (what we have today)
- by prefix (e.g. `Dockerfile.<something>`
- by exact name (e.g. `Dockerfile`)

Support docker

---

kernel/src/analysis/analyze.rs
kernel/src/analysis/tree_sitter.rs

Today, some rules have unecessary matches as reported by @dastrong. We need to ensure there is a capture before we trigger the `visit` function.
Make sure there is a capture before we start the `visit` function. Add a test to make sure we do not have any regression.

prevent unecessary execution of visit function

---

.github/workflows/integration-tests.yaml
.gitignore
cli/src/file_utils.rs
misc/integration-test-repo.sh
misc/test-production-rules.py

We want to make sure that all rules released in production are working in both the CLI and the server.
The solution showed in this PR is for the **CLI ONLY**.
A python script (`test-production-rules.py`) test production rules and verify that the number of expected annotations match the number of violations reported by the CLI.
We will do a follow-up to test the server.

Add integration tests for production rules

---

.github/workflows/integration-tests.yaml

Update time for integration tests, run before to make sure it executes when we wake up.

Update time for integration tests

---

Cargo.toml
bins/src/bin/datadog-static-analyzer-server.rs
versions.json

Some server processes are still alive in the IDE despite the keepalive timeout has been hit.
Instead of calling `exit()`, we are correctly shutting down the rocket server when we hit a keepalive timeout so that the socket and all other important resources are cleaned up.
If all fails, we call `abort()` to abort the process.

Exit the server gracefully

---

bins/Cargo.toml
bins/src/bin/datadog-static-analyzer-server.rs
cli/src/file_utils.rs
cli/src/model/datadog_api.rs
server/src/request.rs

Fixes #120 
If we're not using the `keep alive` functionality, we will just wait for the Rocket thread to finish.
If not, we will await for the first occurrence. Either the Rocket thread finishes (for instance, due to a panic...) or the keep alive functionality notifies the shutdown and causes the `shutdown handle` to finish.
I took the time to fix some clippy issues. It was impossible to even commit without doing `--no-verify`. I'm afraid potential contributors may be facing the same issue.  Is that expected or are you not getting that at all when trying to commit to the repo?
IDE-1744

fix(shutdown): correctly handle rocket errors

---

bins/src/bin/datadog-static-analyzer-server.rs
cli/src/file_utils.rs

In the IDE we have to deal with some scenarios where the server must be restarted. This basically means that we have to kill the server and restart it again. The most prominent use case for this scenario is when we receive a new binary update.
The main problem here is that we may need to restart the server from an IDE instance that didn't spawn the process, so we need to use several strategies to share the process id amongst instances which are error prone or not reliable. Specifically, in VS Code, we have some constraints around that. 
Aside from that, we have to use different approaches for each of the OS we support in some of the cases, so with this proposed solution we think we would greatly simplify our problem.
- It would allow for all the IDEs to use it, without having to replicate …

feat(shutdown): add new shutdown endpoint under a flag

---

bins/src/bin/datadog-static-analyzer-server.rs
server/src/constants.rs

While integrating the static analyzer with VS Code we found it would be useful to get some extra information about the server in each request so we can optimize the amount of request we do to the server itself.
For instance, if a particular instance of VS Code is pinging to a server that has been updated by another instance, we may have the case where some instances are not aware that they're pinging now to a different version of the server.
Now, we have abused some of the VS Code APIs to broadcast this to the rest of the instances, so they can react accordingly and clear their cached information (supported languages...).
Although this works, we cannot guarantee that these messages are properly broadcasted in a timely manner. In the end, we're using an API that was not conceived for that. …

feat(headers): add custom headers with server information

---

bins/src/bin/datadog-static-analyzer-server.rs

Now only the ping requests are extending the life of the server if keep alive is on. No other requests matter.
Added a new fairing/middleware so that if the keep alive functionality is on, all the requests will slide the keep alive counter.
Built on top of #126 
IDE-1896

feat(server): extend the keepalive behavior to all requests 

---

bins/Cargo.toml
bins/src/bin/datadog-static-analyzer-server.rs
server/src/constants.rs

Similar to what we introduced in #125 it would be valuable to us to have information about the keepalive functionality in preparation for when we're dealing with web scenarios or servers that are not controlled by us.
Added a new custom header `X-static-analyzer-server-keepalive-enabled` with that information.
The PR also unifies the server state and gets rid of the `lazy-static` dependency, as we don't need it for our purposes given that we can rely on Rocket state.
DE-1900

feat(server): added new keepalive custom header

---

Cargo.toml
cli/src/datadog_utils.rs
versions.json

When we run an analysis with a `DD_SITE` env var set, we're mistakenly using the default site.
This is because `get_datadog_variable_value` adds `DD_` and `DATADOG_` prefixes to the string it accepts, so currently we end up looking for a variable named either `DD_DD_SITE` or `DATADOG_DD_SITE`.
Remove `DD_` from `DD_SITE`, so the `get_datadog_site` behaves properly.
Leave it be.
None.

fix(cli): remove DD_ prefix

---

bins/src/bin/datadog_static_analyzer_server/cli.rs
bins/src/bin/datadog_static_analyzer_server/endpoints.rs

For the IDEs to understand some of the common server failures properly we need better exit codes.
For instance, when the port is already bound, the server was panicking, which in rust means 101, so we were unable to make sense of this panic compared to others like the one the server was throwing when the parameters are unknown.
Removed some of those panics and handled the errors by exiting with a more meaningful error code.
If this gets merged it would be nice to do a release as VS Code will leverage those error codes to better assist the user.
IDE-2014

feat(server): improve error codes

---

.vscode/launch.json

While working in the static analysis integration for VS Code I find useful to debug the server to get insights on some of the errors.
I added a launch configuration for vs code to start a debug session for the server.
I know this works only for VS Code and maybe the owners of the repo don't want to commit IDE related files, but since VS Code is widely used I pushed this for your consideration.

chore(server): add launch debug configuration for vscode

---

Cargo.toml
cli/src/sarif/sarif_utils.rs
versions.json

A result in a SARIF report using the remove edit type incorrectly reports the start position for the end positions. 
First, use the actual end positions.
Second, since the field is an option, either get the value or set a default position just like we do for an update edit type.
None.
Related to: STAL-834
Here's a before and after screenshot of an analysis I ran locally showing the correct ending positions.

fix(cli): remove edit type end positions

---

.github/workflows/sca.yml
server/src/tree_sitter_tree.rs

As we released SCA analysis, we need to dogfood more our products
Adding a job to run SCA analysis at each push
The `return` removed is because of `clippy` that would not commit otherwise.

Adding sca analysis

---

.github/workflows/production-rules.yaml
cli/src/file_utils.rs

We want the CLI to work for Go rules
1. Enable the language
2. Add all production rules to be tested in the CI pipeline.

[STAL-1168] Enabling go for the CLI

---

versions.json

We never published version `0.2.0` and `0.1.9`. Therefore, they should not be in the `versions.json`
Remove these versions from the `versions.json` file.

[STAL-1051] remove unpublished version

---

crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/model/analysis.rs

We want users to be able to filter violation for a specific ruleset. If users only put `#no-dd-sa`, all violations are filtered on the next line. If the user puts `#no-dd-sa ruleset1/rule2`, only `ruleset1/rule2` is filtered.
When we analyze a file, we first build the list of
1. lines to ignore all rules
2. lines to ignore only some rules
After the engine execution, we filter the results according to this list.
Tested locally with [this file](https://github.com/juli1/rosie-tests/blob/main/yaml_load.py).
If putting `#no-dd-sa` on line 2, I get
```
Found 4 violations in 5 files using 91 rules within 1 secs
```
If putting `#no-dd-sa   python-security/yaml-load` on line 2, I get
```
Found 4 violations in 5 files using 91 rules within 1 secs
```
If put nothing, I get
```
Found 5 violations in …
```

[STAL-1259] filter violation for specific rule

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/file_utils.rs
crates/cli/src/model/cli_configuration.rs

We want to support multiple subdirectories to analyze with the static analyzer
Support multiple `--subdirectory` options.
```
cargo run --bin datadog-static-analyzer -- -i <directory>-o /tmp/plop.json -u <subdir1> -u <subdir2>
417/417Found 527 violations in 442 files using 73 rules within 30 secs
```
```
cargo run --bin datadog-static-analyzer -- -i <directory>-o /tmp/plop.json -u <subdir1>
148/148Found 103 violations in 159 files using 73 rules within 4 secs
```
```
cargo run --bin datadog-static-analyzer -- -o /tmp/plop.json  -i /Users/julien.delange/dd/dd-source --subdirectory domains/static-analysis --subdirectory domains/ci-app --subdirectory ../../
sub-directories are not safe and point outside of the repository
```

[STAL-1265] support multiple subdirectories

---

crates/bins/Cargo.toml
crates/bins/src/bin/datadog-static-analyzer-test-ruleset.rs

Compilation warnings caused the pre-push hook to fail, preventing creation of pull requests.
* Update rocket to 0.5.0 since RC3 was known to cause those 'unused import' warnings.
* Use `.first()` instead of `.get(0)`

Fix compilation warnings.

---

LICENSE-3rdparty.csv
crates/bins/Cargo.toml
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/Cargo.toml
crates/cli/src/lib.rs
crates/cli/src/violations_table.rs

After the analyzer is run, the standard output only says that "N violations were found", but the actual list of violations must be found elsewhere, which creates unnecessary friction.
Display the list of found violations as a table at the end of the run.
Uses the `prettytable-rs` crate, which can lay the table out automatically and also has formatting options to avoid displaying too many borders.

[STAL-626] Display a list of violations at the end of each run.

---

LICENSE-3rdparty.csv
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/Cargo.toml
crates/cli/src/model/cli_configuration.rs
crates/cli/src/sarif/sarif_utils.rs
crates/static-analysis-kernel/src/model/rule.rs

When running diff-aware scanning, we need to generate digest of the configuration to know on what configuration the run has been done. This way, we make sure that when doing diff-aware scanning, we are using the same configuration. A user that modifies the configuration cannot have diff-aware scanning.
We are generating a digest of the configuration and insert it into the SARIF report. The digest is a `md5` digest of the configuration and the configuration includes the directories used to scan the repository as well as the list of rules (so that if a rule change, we are not doing a diff-aware scan).
Added a dependency on the `md5` crate and added if in the `LICENSE-3rdparty.csv`

[STAL-1260] Generate configuration digest for diff-aware scanning

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/file_utils.rs

We want to filter the larger files and avoid scanning files larger than a given size.
We already had the function `filter_files_by_size`. We just need to plumb it correctly. This PR correctly plugins the function in the pipeline.

Filter files by size

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/datadog_utils.rs
crates/cli/src/model/datadog_api.rs
misc/integration-test-docker.sh
misc/integration-test-python.sh

We want to be able to run the analyzer with the default rules, regardless if there is a `static-analysis.datadog.yml` or not.
Load all the default rules at startup-time by using the default ruleset endpoint and run the tool on all of them.
Also display a disclaimer if no file is passed and invite the user to read our documentation.

Running without static-analysis.datadog.yml file

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/config_file.rs
crates/cli/src/model.rs
crates/cli/src/model/config_file.rs
crates/cli/src/model/serialization.rs
misc/integration-test-js-ts.sh

We are going to enable and disable rules on a path/file pattern basis.
This PR updates the configuration file to accept the new format.
The new format is backwards compatible, so existing configurations will still work.
The new configuration directives are not implemented, so they won't work even if the user adds them.
The documentation for the format will be updated when the functionality is enabled.

Update configuration file format for path-based inclusion/exclusion

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/constants.rs
crates/cli/src/datadog_utils.rs
crates/cli/src/file_utils.rs
crates/cli/src/sarif/sarif_utils.rs

We want to add a unique fingerprint to each violation in the sarif file. 
This is reported in the `partialFingerprint` in the SARIF file. This hash contains the content of the file and some other meta information to attempt to make it unique.
Ran the tool on a large repo and disable the generation of fingerprints. Run on 1630 files for Go and YAML. The objective is to see the performance impact.
To disable fingerprinting, we just added `let fingerprint_option = None;` in the `sarif_utils.rs`
Then, built each version with `cargo build -r`
```
Found 1500 violation(s) in 1630 file(s) using 105 rule(s) within 12 sec(s)
./target/release/datadog-static-analyzer --directory  --format sarif --output  57.55s user 5.52s system 435% cpu 14.486 total
```
```
Found 1500 violation(s) in 1630 file(s) …
```

[STAL-1418] Violation fingerprints

---

crates/static-analysis-kernel/src/analysis/javascript.rs
crates/static-analysis-kernel/src/analysis/js/stella.js

When in a rule, we do `console.log(var)`, it logs nothing, which is a bad user experience. We should log a string.
Force the `console.log` to log a string by prefixing the entry in the logs with `""`.
Adding another dependency by using the `deno` console. I prefer not to introduce another dependency for now, this should do the work, especially since output is for debug only.

Fix Stella console

---

FAQ.md
README.md
crates/cli/Cargo.toml
crates/cli/src/sarif/sarif_utils.rs

Internal users mentioned that the [SARIF generation](https://dd.slack.com/archives/C066HQ6K8BX/p1709221692867909) can be very long.
It is not a solution of the problem, rather a code cleanup and documenting the issue.
1. Cleaning the code and removing code that does potential unsafe `unwrap`
2. Printing mode debug information that could help diagnose the issue
3. Adding a FAQ section to inform users
We still need to see potential solution for this problem

[STAL-1457] add better handling of git SHA finding

---

.github/workflows/verify-schema.yaml
README.md
schema/Makefile
schema/README.md
schema/examples/invalid/gitignore-wrong-type.yml
schema/examples/invalid/ignore-wrong-type.yml
schema/examples/invalid/maxfilesize-wrong-type.yml
schema/examples/invalid/only-wrong-type.yml
schema/examples/invalid/rules-arguments-wrong-type-list.yml
schema/examples/invalid/rules-arguments-wrong-type-map-of-list.yml
schema/examples/invalid/rules-arguments-wrong-type-string.yml
schema/examples/invalid/rules-ignore-wrong-type.yml
schema/examples/invalid/rules-only-wrong-type.yml
schema/examples/invalid/rules-wrong-type-list.yml
schema/examples/invalid/rules-wrong-type-string.yml
schema/examples/invalid/rulesets-absent.yml
schema/examples/invalid/rulesets-empty.yml
schema/examples/invalid/rulesets-ignore-wrong-type.yml
schema/examples/invalid/rulesets-indentation.yml
schema/examples/invalid/rulesets-only-wrong-type.yml
schema/examples/invalid/rulesets-wrong-type-map.yml
schema/examples/valid/arguments.yml
schema/examples/valid/complex1.yml
schema/examples/valid/complex2.yml
schema/examples/valid/extensions.yml
schema/examples/valid/simple.yml
schema/examples/valid/with-gitignore.yml
schema/examples/valid/with-maxfilesize.yml
schema/schema.json

The IDE plugins need to be able to parse the static analyzer configuration file. Therefore, there needs to be a definition they can use to build their parser.
A schema definition, with its tests, that defines the format.

JSON Schema for the static analyzer configuration file.

---

LICENSE-3rdparty.csv
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/Cargo.toml
crates/cli/src/config_file.rs
crates/cli/src/file_utils.rs
crates/cli/src/model/cli_configuration.rs
crates/cli/src/model/config_file.rs
crates/cli/src/path_restrictions.rs

The `glob_match` crate has a bug with a pattern like `**/*test*.py` , where a file like `abc/test/def/test.py` does not match.
Or even `t/test.py` does not match.
See https://github.com/devongovett/glob-match/issues/9 for issue.
The `globset` crate does not have that bug and is pretty fast too.
`globset` has a separate compilation step, so I do it during configuration parsing.

Replace glob_match with globset

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/rule_utils.rs
crates/static-analysis-kernel/src/model/rule.rs
misc/integration-test-python.sh

The problem is reported by @yoannmoinet: we want to have an option to exit a non-zero code if there is at least one violation. 
We offer the option for different severity.
- `--fail-on-any-violation=<list-of-severities>` fail if there is at least one violation with a severity from the list of `<list-of-severities>`
Added unit tests for the counting as well as an integration tests.
See below for manual testing.
Incorrect severity
```
datadog-static-analyzer --directory /Users/julien.delange/git/rosie-tests --output /tmp/plop.plop --fail-on-any-violation=none,warning.notice,error        14:02:18
thread 'main' panicked at crates/bins/src/bin/datadog-static-analyzer.rs:208:48:
cannot map severity: "unknown severity"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace …
```

[STAL-1496] add option to fail if there is any violation

---

.vscode/launch.json
LICENSE-3rdparty.csv
crates/static-analysis-kernel/Cargo.toml
crates/static-analysis-kernel/src/config_file.rs
crates/static-analysis-kernel/src/model/config_file.rs
crates/static-analysis-kernel/src/path_restrictions.rs

I was trying to serialize a ConfigFile instance and expected to get a valid YAML file. Unfortunately, the serialization for the rulesets was not implemented resulting in an invalid YAML according to the schema of our configuration file.
This PR adds support for proper serialization, ignoring both `Option::None` and some default values. This helps to avoid having values showing `null`, `{}` or `[]`
Added a few tests for the new functionality and a vscode debug configuration to help debugging the tests, if needed.
Also, I added a new crate called [indexmap](https://crates.io/crates/indexmap), which was needed to keep the insertion order of the keys in the maps. This is critical for serialization purposes as the `rulesets` array has a weird convention where the first key must be the ruleset …

feat(kernel): add support for ConfigFile serialization

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/datadog_utils.rs

Add ruby as a default language so it's being picked up when we launch the tool without any ruleset.
Add the language in the default languages
We are also adding the accurate number of rules used. If rules for a language not used was loaded before, it was counting towards the total number of rules used. We now count the exact number of rules used during the scan.

[STAL-1362] add ruby in default languages

---

crates/bins/src/bin/datadog-static-analyzer.rs

Configuration error messages look exactly like "something went horribly wrong" error messages.
Display a slightly friendlier message.
In the future we may try to have messages that explain what went wrong in simpler words.

Display a nicer error message for configuration file errors

---

crates/static-analysis-kernel/src/analysis/file_context/go.rs
doc/go.md

Adding documentation for package alias
Add a directory `doc` and a file per language to release language-specific information.
This PR started with a file `go.md`

[STAL-1557] add documentation for go

---

crates/cli/src/file_utils.rs
crates/cli/src/sarif/sarif_utils.rs
crates/static-analysis-kernel/build.rs

The fingerprint relies only on the content of the file and line. If two violations from two different rules put a warning on the same line, they have the same fingerprint.
Add the rule name in the fingerprint so that if we have two rules on the same line, they will have another fingerprint.

[STAL-1575] Fingerprint improvements

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/sarif/sarif_utils.rs

We do not have the execution time in the sarif metadata
Add the execution time in the sarif metadata
To avoid having too many arguments, the `generate_sarif_report` now use a structure that includes all metadata required to generate the report.

Add execution time in sarif reports

---

crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/static_analysis_config_file.rs

The ignore rules were not correctly generated and were only taking into consideration the first level of directories.
Use the proper glob: '**'
IDE-2566

fix(ide): use proper glob for ignore rule creation

---

crates/static-analysis-server/src/request.rs

The IDE plugins used to apply ignore-paths locally, but now it's left to the server.
Check the global ignore/only setting early in the analysis handler and exit early.

Apply global ignore/only in server

---

README.md
crates/bins/src/bin/datadog-static-analyzer.rs
crates/static-analysis-kernel/src/config_file.rs
crates/static-analysis-kernel/src/lib.rs
crates/static-analysis-kernel/src/rule_overrides.rs
crates/static-analysis-server/src/request.rs

Sometimes users want to change the severity or category of a violation.
Users can specify per-rule severities and categories and we use those when specified.

Override a rule's severity and category when specified in the configuration file

---

.vscode/settings.json

With the introduction of `vectorscan` the [rust-analyzer extension](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) which is the main LS extension for Rust in VS Code, stopped working. 
Even if users would follow the [build instructions](https://github.com/DataDog/datadog-static-analyzer/tree/main/crates/vectorscan-sys) provided in the repo, the analyzer would fail to compile, leading to it not working.
The main issue with this is that devs would have it more difficult to get build errors at development time.
The solution is to use a hidden flag: `rust-analyzer.cargo.allFeatures` and set it to false. This, in conjuction with having the proper tools `boost, cmake and ragel` installed, does the trick.
I also added this other flag: …

fix(ra): fix rust-analyzer for vs code users

---

crates/static-analysis-kernel/src/config_file.rs
crates/static-analysis-kernel/src/model/config_file.rs

Serialization of the `ArgumentValues` struct is not properly done. This causes issues for the IDEs when using serialization for ignoring rules.
So, this:
```yaml
- typescript-code-style:
rules:
max-params:
arguments:
max-params: 3
```
becomed:
```yaml
- typescript-code-style:
rules:
max-params:
ignore:
- '**'
arguments:
max-params:
by_subtree:
'': '3'
```
Added a custom serialization method and some tests covering it.
Feel free to modify or expand this implementation. I was wondering why we need the `ArgumentValues` at all given that we chose to ignore the `by_subtree` property. If there's no point, maybe we could use a HashMap or a a tuple struct. Although, I guess we would still want to have a custom serializer/deserializer to avoid having this case:
```yaml
arguments:
max-params:
'': …
```

fix(serialization): correctly serialize arguments

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/csv.rs
crates/cli/src/file_utils.rs
crates/cli/src/model/cli_configuration.rs
crates/cli/src/rule_utils.rs
crates/cli/src/sarif/sarif_utils.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/javascript.rs
crates/static-analysis-kernel/src/model/rule.rs

We want to be able to diagnose potential bottlenecks.
We are now collecting more traces and data
- time to parse the tree-sitter query
- time to query the nodes in an AST
- time to parse the source code
When the `-x` flag is set `--performance-statistics`, we show the query node time and the execution time for each node.
We also show the time to convert a rule to an internal rule. We also show the files that are the slowest to parse.
This would then help us to investigate performance bottlenecks.

[STAL-1701] add more performance statistics

---

crates/static-analysis-kernel/build.rs

The YAML parser currently cannot be loaded in the browser as a WASM module, due to it being unmaintained and using C++, which tree-sitter has now deprecated upstream
Use a maintained fork that has rewritten the scanner in C and has fixed some other bugs
N/A
This only updates a dependency

[STAL-1645] fix: use maintained and up-to-date yaml grammar

---

crates/cli/src/model/cli_configuration.rs

We want to add more instructions when we fail to get informations about the repository being scanned for diff-aware. We found that when failing to get the repository, `libgit2` may fail to get the repository. We need to inform the user about potential issues.
See [this ticket in `datadog-static-analyzer-github-action`](https://github.com/DataDog/datadog-static-analyzer-github-action/pull/31) for more details.
Add more information about the cause with potential workarounds on the standard error.

[STAL-1921] More instructions when we fail to get the repository for diff-aware

---

.github/workflows/release.yml
.github/workflows/rust.yaml

Our build for for x86 macOS has started failing, because at some point `make` is passed `-mcpu=apple-m1`.
GitHub is currently moving `macos-14` (currently `macos-latest`) runners to aarch64.
Without actually digging for where this flag is getting set, I presume that some script assumes it is building for the native architecture, and so it detects aarch64 and sets the corresponding flag, despite us really wanting to compile x86.
As a workaround, this PR pins our x86 macOS runner to macos-13, which runs x86 natively.
You can see from this manually-run workflow that pinning to macos-13 solves this issue: https://github.com/DataDog/datadog-static-analyzer/actions/runs/8886167438/job/24399431838
(NOTE: the job overall failed because I ran this as an ad-hoc, incomplete release -- however, you …

[STAL-1986] Fix macOS x86 GitHub Actions build

---

crates/bins/src/bin/datadog-export-rulesets.rs
crates/bins/src/bin/datadog-static-analyzer-test-ruleset.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/datadog_utils.rs
crates/cli/src/model/cli_configuration.rs
crates/cli/src/model/datadog_api.rs
crates/cli/src/rule_utils.rs
crates/cli/src/sarif/sarif_utils.rs
crates/static-analysis-kernel/src/model/rule.rs
crates/static-analysis-server/src/model/analysis_request.rs
crates/static-analysis-server/src/request.rs
misc/test-production-rules.py

We would like to create a system in which we can test rules before adding them to the pool of production-ready rules.
As part of an effort to build a system in which rules can be tested but not be disruptive, we're adding an `is_testing` boolean flag on rules. This tag can be used for filtering, tagging, etc.
This PR adds handling to the analyzer for the `is_testing` boolean flag on rules retrieved from the Rules API. 
Create a ruleset that has both a testing rule and a non-testing rule. Populate with rules that are known to have violations in the datadog-static-analyzer-test-repo.
Make the config use the test ruleset:
```
~/g/s/g/D/datadog-static-analyzer: cat ../datadog-static-analyzer-test-repo/static-analysis.datadog.yml          
rulesets:
- celia-testing
```
Run a scan without …

[STAL-1686] Add is_testing to rules

---

crates/static-analysis-kernel/src/config_file.rs
crates/static-analysis-kernel/src/model/config_file.rs

We'll need to add more configuration options soon, and the current code is excessively complex. This simplifies it and suggests easy ways to add new stuff later.
For `NamedRulesetConfig` I used the `StringOrStruct` thing instead of the enum like in `ArgumentValues` so that, if one of the fields in the ruleset config fails to parse, we'll get a specific error for that field. This happens because it sees a string or a map and commits to that while deserializing. Otherwise it will try both options, see that both fail, and we just get a generic "expected a string or ruleset configuration" error.

Use higher-level constructs for configuration serializer/deserializer.

---

DEVELOPMENT.md
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/model/cli_configuration.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs

Fetching the branch is currently having some issues. We are testing another way to get the current branch.
The additional `.clone()` is to bypass a noisy `clippy` check

[STAL-2007] debug static analyzer

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/constants.rs
crates/cli/src/git_utils.rs
crates/cli/src/lib.rs
crates/cli/src/model/cli_configuration.rs

In Gitlab pipelines, there is no clean and easy way to get the current branch (see [thread](https://forum.gitlab.com/t/why-i-cant-get-the-branch-name/72462)). The branch cannot be fetched by existing mechanism, it is fetched through variables.
When we build the request to get diff-aware information, try to get the information in this order
1. Get it from the repo
2. Get it from the CI environment (here, GitLab)
3. Otherwise, fail

[STAL-2007] Handle branch from Gitlab pipelines

---

crates/static-analysis-kernel/src/model/rule.rs
crates/static-analysis-server/src/model/analysis_request.rs
crates/static-analysis-server/src/request.rs
misc/test-production-rules.py

When releasing version [0.3.3](https://github.com/DataDog/datadog-static-analyzer/pull/345) of the analyzer, we started having 422s. This was due to the front-end not sending `is_testing` if `is_testing` was unset. The IDE integration would have the same issue. This PR does the following to address this issue:
1. Adds a default value (false) if `is_testing` is empty in the Rule struct.
2. Remove the `is_testing` field from the ServerRule struct.
3. Updates the `test-production-rules.py` integration test to expose the error if it fails, rather than just `returned non-zero exit status 1.`
- However, there could possibly be a cleaner way of surfacing the error. The current output is 
```
Testing ruleset python-best-practices on the CLI
Testing rule special-methods-arguments
Traceback (most …
```

[STAL-1686] Follow-up for handling rules marked as `is_testing`

---

crates/bins/src/bin/datadog-static-analyzer.rs

Some repository URL may contains CI token.
Never log the repository URL

[STAL-2007] remove repository url from logs

---

Cargo.toml
crates/static-analysis-kernel/Cargo.toml

We have warnings when building the analyzer.
```
warning: Patch `cc v1.0.83 (https://github.com/rust-lang/cc-rs?tag=1.0.83#bfc3ba41)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
```
For context, we [hardcoded the version](https://github.com/DataDog/datadog-static-analyzer/pull/210) before in this PR because we had build issues.
Upgrade to the latest version.

update cc dependency

---

crates/bins/src/bin/datadog-static-analyzer.rs

When a rule fails to convert to a rule internal, we do not know what is the rule.
Show the rule that fails.
**Before**
```
Error: cannot convert to rule internal
Caused by:
Query error at 9:18. Invalid node type string_literal_content
```
**After**
```
Error: cannot convert csharp-best-practices/strings-with-one-char to rule internal
Caused by:
Query error at 9:18. Invalid node type string_literal_content
```

show rule that fails to convert

---

crates/static-analysis-kernel/build.rs

The c-sharp grammar at its current revision does not correctly parse a lot of newer C# syntax, leading to false positive reports due to tree-sitter's error recovery doing a poor job sometimes.
Update the C# grammar to the latest revision, which *can* parse these new features
Related - 1864/1865

[STAL-1863] fix: update c-sharp grammar for parsing improvements

---

crates/bins/src/bin/datadog-export-rulesets.rs
crates/bins/src/bin/datadog-static-analyzer-test-ruleset.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/datadog_utils.rs

When using the Analyzer via the CLI, all rules, including testing rules, should be included. 
By hard-coding that all rules, including testing rules, should be pulled from the API, we remove the complexity associated with parameterizing whether or not testing rules should be included. The con of including testing rules by default is virtually only that additional results are in the resulting SARIF file. When the SARIF file gets sent to Datadog, violations from testing rules are hidden in the UI by default (but is easily accessed via a toggle). The pro of including testing rules by default is that it reduces the number of places a user needs to specify that testing rules should be included.
1. Making the query param `exclude_testing_rules` instead of `include_testing_rules`. The con of …

[STAL-2057] Hardcode include testing rules in CLI

---

Cargo.toml
versions.json

Includes the C# grammar updates - so we can get this out to customers who need the fixes

Release 0.3.4

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/src/model/config_file.rs
crates/static-analysis-kernel/src/path_restrictions.rs
crates/static-analysis-server/src/request.rs

This PR makes `is_allowed_by_path_config` a member function of `PathConfig`, which removes external dependencies on `path_restrictions.rs`.
We want to add the ability to have per-subtree rule severity overrides, but before we do that, we need to refactor some of the code to generalize per-subtree overrides.
I've split the refactor into 6 PRs to make them manageable sizes. See https://github.com/DataDog/datadog-static-analyzer/tree/jacobotb/STAL-1832/severity-per-dir/99-final for the intended final state.
Future PRs will move the `ArgumentProvider` to a separate file, separate the configuration file YAML parsing from its internal representation, add a `BySubtree` type, encapsulate per-rule configurations, and finally add the per-subtree rule severity override.

Use a member function of PathConfig to check if the path config allows a file.

---

crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/model/analysis.rs
doc/ignore-rule.md
schema/examples/invalid/disable-ignore-generated-files.yml
schema/examples/valid/disable-ignore-generated-files.yml

We want to be able to ignore rules for the complete file.
If a user wants to ignore rules for a complete file, they need to put a `no-dd-sa` directive at the top of the file.
This follows what eslint is doing (see [here](https://evanhahn.com/disable-eslint-for-a-file/) or [here](https://stackoverflow.com/questions/34764287/turning-off-eslint-rule-for-a-specific-file))
1. Documented all changes in a new markdown file with examples.
2. Adding some old schemas file I forgot to add in a previous PR about ignoring generated files.

[STAL-2139] Ignore rules for the whole file

---

crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/static_analysis_config_file.rs
crates/static-analysis-kernel/src/config_file.rs
crates/static-analysis-kernel/src/model/config_file.rs

Removes all the YAML parsing functionality from `ConfigFile` and moves it to the `src/config_file.rs` file. This PR also adds a `config_file_to_yaml` function, to be used instead of a direct call to `serde_yaml::to_str`. The existing unit tests pass without changes to their inputs or outputs.
These changes separate the YAML representation of the configuration from its binary representation, which lets us have each one in a convenient form for its intended use.
For example, in the YAML, the rulesets are defined in a list, while in the `ConfigFile` they are a map. With the original representation, the parsing code was quite awkward. Now it just parses as a list, and we convert it to a map when we generate the `ConfigFile` object.
This will make it easier to create and use a special data …

Split configuration data object and parsing code

---

crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/arguments.rs
crates/static-analysis-kernel/src/config_file.rs
crates/static-analysis-kernel/src/model/config_file.rs

Creates a `BySubtree` type that stores values that depend on the specific location in the repository tree where a file is located.
This replaces the one-off `ArgumentValues` struct, and it will be used for per-subtree rule severity overrides.
The key for this type is a new `SplitPath` type that contains the split components of a pathname. This encourages the pattern where the `SplitPath` is created once for a file name and then used multiple times, instead of splitting it for every access to a `BySubtree` object. This will be more important as more uses of `BySubtree` are added.
We want to add the ability to have per-subtree rule severity overrides, but before we do that, we need to refactor some of the code to generalize per-subtree overrides.
I've split the refactor into 6 PRs to make …

Add a specific type for values that depend on the subtree

---

crates/static-analysis-kernel/src/analysis/analyze.rs

We detected that comments preceded by a TAB and without any whitespace between the comment symbol (`//`, `#`...) and the text, were ignored.
Basically, while parsing the rules, we were getting `<tab> rule`, as the split is done using the empty string char. This was later on invalidating the equation of strings.
The solution is simply trimming the strings.
I added a test covering this case for 3 sets of languages/comment types (python, java, javaScript).
STAL-2247

fix(analyzer): fix 'lines to ignore' parsing functionality

---

crates/cli/src/constants.rs
crates/cli/src/datadog_utils.rs

We will need to have the static analyzer call our internal API endpoints with JWT tokens for auth. This lets the program that runs the static analyzer provide the hostname and JWT token.
A `DD_HOSTNAME` envvar and a `DD_JWT_TOKEN` envvar. Those are read when requests are built and used if present.
`DD_HOSTNAME` has priority over `use_staging` and `DD_SITE`; `DD_JWT_TOKEN` is used if `DD_API_KEY` and `DD_APP_KEY` are not available.

Add the ability to call other endpoints with JWT tokens.

---

crates/cli/src/datadog_utils.rs
crates/cli/src/model/datadog_api.rs

Currently, if an error is returned from the api when fetching a ruleset, we still attempt to parse it as if it were a valid response, leading to a parsing error which is the error the user sees. This is really incorrect as it does not help diagnose the problem on the user's end to figure out what's actually wrong.
The solution is to start actually handling errors that are not successes from our api, we should parse the error message, which is also json, and extract the info from there to show to the user. Currently, we could get a 400 for bad parameters in the URL, a 404 for a ruleset that wasn't found, and a 500 for an internal server error (w.r.t custom rules, which is not yet available)
Keep poorly handling server errors
There are some changes that are just naming (e.g. Api -> API), so …

[STAL-2179] Add better error message for ruleset fetch failure

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-kernel/src/model/common.rs

Currently, we do not support Bazel (Starlark) files. Even though it is very similar to Python, there are some slight differences, which would make it not ideal to reuse the grammar for Python for Starlark files.
Add the Starlark grammar to the analyzer itself, which is fetched from https://github.com/tree-sitter-grammars/tree-sitter-starlark. This grammar accounts for the minute differences between Starlark and Python, making it a good candidate to add in the analyzer. This will allow us (and customers down the line) to begin writing rules targeting Bazel/Isopod files
Not adding another grammar and reusing the Python grammar for Starlark
A couple notes, since I tacked on a few code changes that are not *directly* needed for this PR, but are more plumbing/nice-to-haves and relate to it …

[STAL-2337] feat: add Starlark support

---

.github/workflows/ghcr.yml
Dockerfile

Currently, it is not trivial for users to pull in the analyzer as a Docker image that they can run or build on top of, nor is it not publicly available on GHCR which is a convenient registry for users to pull in such images.
Add a Dockerfile + a ci workflow that publishes this image to GHCR every time we publish a release.
The workflow is pretty simple, and does the following
- Check out the repo
- Set up QEMU (for arm64 images) and Docker Buildx
- Logs into GHCR to authenticate publishing under this repo
- Extracts relevant metadata based on the event, for a push it will use the commit sha, but in the case of our release, it will use the tag (e.g. v0.20.0) *and* `latest`, which is just a convention used for Docker images
- Builds the image itself, note that because of arm emulation this …

[STAL-1906] feat: add Dockerfile + ci workflow to publish to GHCR

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-kernel/src/model/common.rs

Currently, we do not support Bash files. We need a way to parse and query bash files, but we do not currently fetch and build a Bash grammar.
Add the Bash grammar to the analyzer itself, which is fetched from https://github.com/tree-sitter/tree-sitter-bash. This will allow us (and customers down the line) to begin writing rules targeting Bash files.
Not supporting bash files
I renamed the python example code string to be prefixed with `PYTHON_` since I added a bash one too, and reused this in the Starlark test hence why the code relating to the Starlark test was modified.

[STAL-2338] feat: add Bash support

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/bins/src/bin/datadog_static_analyzer_server/fairings.rs
crates/cli/src/model/cli_configuration.rs
crates/static-analysis-kernel/src/arguments.rs
crates/static-analysis-kernel/src/model.rs
crates/static-analysis-kernel/src/model/config_file.rs
crates/static-analysis-kernel/src/model/diff_aware.rs
crates/static-analysis-kernel/src/model/rule.rs
crates/static-analysis-kernel/src/path_restrictions.rs

When we generate the config hash for diff-aware, some parts of the configuration are not being included, especially the results about where to apply the rules (`only` and `ignore` configuration attributes).
Add a trait `DiffAware` that contains the method that needs to be implemented for each configuration element that may be used to calculate the hash for diff-aware. This trait is then implemented for many configuration elements, including the one for `only` and `ignore` attributes.

[STAL-2336] Include paths configuration for diff-aware hash

---

crates/static-analysis-kernel/src/analysis/ddsa_lib/bridge/context.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/context.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/context/file.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/context/file_tf.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/extension.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/js.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/js/__bootstrap.js
crates/static-analysis-kernel/src/analysis/ddsa_lib/js/context_file.js
crates/static-analysis-kernel/src/analysis/ddsa_lib/js/context_file.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/js/context_file_tf.js
crates/static-analysis-kernel/src/analysis/ddsa_lib/js/context_file_tf.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/v8_ds.rs

Currently, implementing a rule that checks for the existence or validity of a similar resource is nearly impossible, and is very difficult to express in the query syntax. The issue that sparked this PR was that given a specific resource, with a type of `foo`, a user wanted to check that a corresponding resource with the type`foo_public_access_block` existed. Implementing this with a query is very difficult with a lot of edge cases and loop holes to consider (e.g. does this corresponding resource come before or after the main one, is it immediately after, etc), and just having all the resources in a given Terraform module exposed nicely in the JS api would be much more preferable, in a way where a user can simply just check every resource and their type and name in a given Terraform …

[STAL-2289] feat: add terraform file context helper in the JS code

---

crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/static_analysis_config_file.rs

Do not error if the user deletes everything in the config file, then tries to onboard from scratch again. The previous code would fail because an empty string is technically invalid YAML.
When we see an empty string as the config, assume there's no config.
This code is used from the IDE-plugin-facing API to modify the config file.

StaticAnalysisConfigFile: do not error if the configuration is empty

---

Dockerfile
misc/github-action.sh

We need a robust way to run our github action with a script that sets up the necessary environment variables and cli arguments without being too hacky with multi-step composite workflows.
Add a `github-action.sh` script (stripped-down version of this [entrypoint.sh](https://github.com/DataDog/datadog-static-analyzer-github-action/blob/main/entrypoint.sh) script) that will set up the necessary environment variables and arguments given the input.
Use the composite workflow [here](https://github.com/DataDog/datadog-static-analyzer-github-action/pull/40)
I talked with Julien about this and this is the solution we came up with, the added benefits are that whenever we add new features to our analyzer, we can update this script here and the container will be updated in one go instead of having …

feat(docker): add github-action.sh CI script

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-kernel/src/model/common.rs

Currently, we do not support PHP files. We need a way to parse and query PHP files, but we do not currently fetch and build a PHP grammar.
Add the PHP grammar to the analyzer itself, which is fetched from https://github.com/tree-sitter/tree-sitter-php. This will allow us (and customers down the line) to begin writing rules targeting PHP files.

[STAL-2456] feat: add PHP support

---

LICENSE-3rdparty.csv
crates/common/Cargo.toml
crates/common/src/lib.rs
crates/common/src/model/position.rs
crates/common/src/utils.rs
crates/common/src/utils/position_utils.rs
crates/secrets/Cargo.toml
crates/secrets/src/scanner.rs

When resolving the line/col based on an index, our previous code did not take into account is there was any emoji/grapheme.
Use `bstr` and use the grapheme iterator to find the right line/col.
Tested against the code we [previously had](https://github.com/DataDog/datadog-static-analyzer/blob/644540d87a6aa39958b7dfbb5d0eaae8e788f919/crates/secrets-core/src/location.rs#L408). Test for the secrets scanning still works.

Fix line/col search in string

---

.github/workflows/check-regressions.yml

We now support PHP in the analyzer and rule editor, and have 10 rules available in prod, so we should check for regressions for this language as well. We also provide default rulesets for PHP as well.
Add two PHP repos to check for regressions, one focused on security and one focused on best practices/code style.
This PR only adds two repos to be checked in the `check_regressions` job.

[STAL-2508] ci: add regression checks for PHP repositories

---

crates/cli/src/datadog_utils.rs

PHP rulesets are not being fetched by default
Fetch them by default by adding PHP to the `DEFAULT_RULESETS_LANGUAGES` array
Testing:
With no configuration file, we can see the default rulesets of `php-security` and `php-best-practices` running.
We can also see the API returning the correct default rulesets here.

[STAL-2508] add php to default rulesets language

---

README.md

Update the messaging for diff-aware to indicate that a full scan will happen when diff-aware is not available.
Update the docs
[Similar PR in Datadog's documentation repo](https://github.com/DataDog/documentation/pull/24194)

[STAL-2445] Update diff-aware messaging

---

crates/bins/src/bin/datadog-static-analyzer-test-ruleset.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/file_utils.rs
crates/cli/src/model/cli_configuration.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/arguments.rs
crates/static-analysis-kernel/src/lib.rs
crates/static-analysis-kernel/src/rule_config.rs
crates/static-analysis-kernel/src/rule_overrides.rs
crates/static-analysis-server/src/request.rs

We have per-rule enable/disable, per-rule arguments, and per-rule severity/category overrides, all spread across three different objects that are initialized separately, passed separately, and used separately.
We will be adding more.
This PR bundles those objects together so only one object needs to be initialized, and only one object needs to be passed to the 'analyze' function.
Since the `analyze` function takes one file name and a list of rules, we can avoid parsing the filename more than once. To that end, the `RuleConfigProvider` has a `config_for_file` function that generates a `RuleConfig` scoped to a particular file, with the file name all parsed up nicely. This is the object that is passed to the `analyze` function.
The `RuleConfig` then has functions to get argument values, …

Bundle the per-rule configurations/overrides

---

crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/config_file.rs
crates/static-analysis-kernel/src/model/config_file.rs
crates/static-analysis-kernel/src/rule_config.rs
crates/static-analysis-kernel/src/rule_overrides.rs
crates/static-analysis-server/src/request.rs
schema/examples/valid/severity.yml
schema/schema.json

Severity overrides are global. We want to be able to set different overrides in different parts of the repo.
Modify the schema so the configuration can take severity values or maps from subdirectory to severity. This also makes the 'per subtree' mechanism general so other things can be per-subtree later on.
This is the last PR of the series.

Per-subtree rule severity overrides

---

crates/bins/src/bin/datadog-static-analyzer-git-hook.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/secrets/Cargo.toml
crates/secrets/src/lib.rs
crates/secrets/src/secret_files.rs

We want to prevent analyzing some files that will trigger false positives by default.
Ignore common files such as `yarn.lock` or `WORKSPACE`. Such files contains `shas` and other sequences with large entropy, which may trigger false positives.

Ignore certain files for secrets

---

crates/cli/src/datadog_utils.rs
crates/cli/src/model/cli_configuration.rs
crates/cli/src/model/datadog_api.rs
crates/secrets/src/model/secret_rule.rs
crates/secrets/src/scanner.rs

To reduce false positives from being raised, we need to pass more data to the rules. The SDS engine also use a `default_included_keywords` which brings additional data used to check for secrets. We did not use them so far but it's suggested to use them to decrease the number of false positives.
Consume the `default_included_keywords`
Scanning a large Java codebase
**Before**
```
Found 1313 secret(s) in 32905 file(s) using 22 rule(s) within 6 sec(s)
```
**After**
```
Found 16 secret(s) in 32905 file(s) using 22 rule(s) within 6 sec(s)
```

Add proximity keywords

---

.github/workflows/release.yml
Cargo.toml
versions.json

We want to release the git hooks
Add a task to release them. Also remove the server from the CLI as it add weight in the bundle. We should instead release the server separately.

Add git hooks release

---

Cargo.toml
LICENSE-3rdparty.csv
crates/bins/Cargo.toml
crates/bins/src/bin/datadog-static-analyzer-server.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/bins/src/bin/datadog_static_analyzer_server/cli.rs
crates/bins/src/bin/datadog_static_analyzer_server/endpoints.rs
crates/bins/src/bin/datadog_static_analyzer_server/fairings.rs
crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/comment_preserver/mod.rs
crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/comment_preserver/models.rs
crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/comment_preserver/reconciler.rs
crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/error.rs
crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/mod.rs
crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/static_analysis_config_file.rs
crates/bins/src/bin/datadog_static_analyzer_server/ide/mod.rs
crates/cli/src/datadog_utils.rs
crates/cli/src/file_utils.rs
crates/static-analysis-kernel/Cargo.toml
crates/static-analysis-kernel/src/model/analysis.rs

The main problem is that the comments of the configuration file are removed after modification due to the deserialization and serialization process. Some users have complained about it.
Added support for comment preservation and pretty formatting.
The last commit fixes some `clippy` warnings that  were triggering when committing or pushing (via cargo-husky). I had to touch some files outside the `ide` folder. For some reason, we're using `-D warnings` locally but not in the CI. I didn't want to modify any of this but I guess it would be nice to reconcile this difference at some point.
https://github.com/user-attachments/assets/1e42b2ee-5b10-4435-a0ea-1c73580178bc
IDE-2599

feat(config): preserve comments in the static analysis configuration file - IDE-2599

---

.github/CODEOWNERS

Before the whole IDE integrations team was a code owner of the IDE folder. As we wanted to enable the auto assignation of reviewers for this repo, we had to enable it for the IDE integrations team. This was causing a problem for the Jetbrains sub-team which uses the IDE Integrations team for their repo. Members of the VS and VS Code team were assigned to their PRs as reviewers.
As they don't want to create a sub team for their repo and they don't want to use the reviewer auto assignation feature, the solution was to create a new subteam specific for this repo.

chore(github): updated the team owning ide

---

Dockerfile

We want to release more tools (git hook and server) into our GHCR image.
Build and add them to the image

Add git-hook and server into GHCR release

---

LICENSE-3rdparty.csv
crates/cli/Cargo.toml
crates/cli/src/sarif/sarif_utils.rs

We want to make sure that when running on Windows, the SARIF files are correctly created and validated. Today, the path are using `\` which breaks the file validation.
Example of file
Running `datadog-ci` against this file.
In `sarif_utils.rs`, ensure that we convert the filenames to using slash. We are using the [path_slash](https://docs.rs/path-slash/latest/path_slash/) rust module for this.
Closes #476 
Tested on a Windows machine.
Example of file after modifications
Running `datadog-ci` against this file.

[STAL-2617] Add Windows Support

---

crates/bins/src/bin/datadog-static-analyzer-git-hook.rs
doc/git-hooks.md
misc/integration-git-hooks.sh

For Git hooks, customers may want to only runs the hook for secrets. We make the static-analysis option a mandatory option that users have to enabled.
Add a flag `--static-analysis` that asks users to specify running static analysis.

make static analysis optional in git hooks

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-kernel/src/model/common.rs

Currently, we do not support Markdown files. We need a way to parse and query Markdown files, but we do not currently fetch and build a Markdown grammar.
Add the Markdown grammar to the analyzer itself, which is fetched from https://github.com/tree-sitter-grammars/tree-sitter-markdown. This will allow us (and customers down the line) to begin writing rules targeting Markdown files.

[STAL-2703] feat: add Markdown support

---

crates/bins/src/bin/datadog-static-analyzer-git-hook.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/config_file.rs
crates/cli/src/datadog_utils.rs
crates/cli/src/git_utils.rs
crates/cli/src/model/cli_configuration.rs
crates/cli/src/model/datadog_api.rs

We want to be able to fetch the configuration remotely.
We attempt to read the configuration file
1. If there is a configuration file, we attempt to get the remote configuration by passing the existing config file and the backend returns the final config
2. If there is no config, we retrieve the remote configuration by passing a `null` configuration to the API
1. We fetch the remote configuration ONLY if we have some API keys defined. Otherwise, we do not even try
2. We added a lot of debug information so that customer will be able to troubleshoot
Tested locally, existing tests should pass
```
cargo run --bin datadog-static-analyzer -- --staging --directory /Users/julien.delange/git/datadog-ci --format sarif --output ~/plop.json  --debug yes 
Finished `dev` profile [unoptimized + …
```

[STAL-2687] Fetch remote config

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-kernel/src/model/common.rs

Currently, we do not support Apex files. We need a way to parse and query Apex files, but we do not currently fetch and build an Apex grammar.
Add the Apex grammar to the analyzer itself, which is fetched from https://github.com/aheber/tree-sitter-sfapex. This will allow us (and customers down the line) to begin writing rules targeting Apex files.

[STAL-2707] feat: add Apex support

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-kernel/src/model/common.rs

Currently, we do not support R files. We need a way to parse and query R files, but we do not currently fetch and build an R grammar.
Add the R grammar to the analyzer itself, which is fetched from https://github.com/r-lib/tree-sitter-r. This will allow us (and customers down the line) to begin writing rules targeting R files.

feat: add R support

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-kernel/src/model/common.rs

Currently, we do not support SQL files. We need a way to parse and query SQL files, but we do not currently fetch and build an SQL grammar.
Add the SQL grammar to the analyzer itself, which is fetched from https://github.com/DerekStride/tree-sitter-sql. This will allow us (and customers down the line) to begin writing rules targeting SQL files.
The SQL grammar repository does not generate and commit the `parser.c` file on the main branch, but rather the `gh-pages` branch, so the commit being used does not exist on the main branch - this is expected

[STAL-2732] feat: add SQL support

---

crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-kernel/src/model/rule.rs
crates/static-analysis-server/src/constants.rs
crates/static-analysis-server/src/request.rs

Currently, our logic for parsing rules into the internal rule representation is a bit brittle when it comes to processing errors. The reason for this is we convert all errors into anyhow errors; using anyhow means we cannot easily pattern-match or check what kind of error was actually returned. The function `Rule::to_rule_internal` can return 5 different types of errors:
- when the rule type is invalid
- when the base64 string is invalid base64
- when the decoded base64 string is invalid utf8
- when the tree-sitter query is missing
- when the tree-sitter-query fails to build
Although some of these errors can be "grouped" together w.r.t. surfacing a public-facing error, it would not make sense to say, show "error-decoding-base64" when the tree-sitter query failed to build.
I've refactored …

[STAL-1489] refactor: handle internal rule conversion errors more pragmatically

---

crates/cli/src/file_utils.rs

We want to be able to tell, just by inspecting the code, that the scanner is not following symlinks.
Set the configuration values, even if they are the defaults, to make it explicit.

Do not follow symlinks while scanning the repo for files to analyze

---

crates/bins/src/bin/datadog-static-analyzer-git-hook.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/config_file.rs
crates/cli/src/datadog_utils.rs
crates/cli/src/file_utils.rs
crates/cli/src/model/cli_configuration.rs
crates/cli/src/utils.rs
crates/static-analysis-kernel/src/model/config_file.rs

1. Default YAML rules are not being pulled
2. We do not show how the analyzer is configured when using remote configuration.
1. Add a `ConfigMethod` that indicates how the analyzer is configured (file, remote or nothing)
2. Add YAML in the list of default languages
With no remote config or file
```
Configuration
=============
version                : 0.4.2
revision               : development
config method          : none (no local file and no remote configuration)
cores available        : 10
cores used             : 8
#static analysis rules : 880
source directory       : /Users/julien.delange/git/tree-sitter-xml
subdirectories         :
output file            : /Users/julien.delange/test.sarif
secrets enabled        : false
output format          : sarif
ignore paths           : …
```

[STAL-2831] Add YAML + configuration method

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/analyze.rs

Currently the Kotlin grammar we use is from a third-party repository, and there are some [open issues](https://github.com/fwcd/tree-sitter-kotlin/issues) w.r.t parsing. Not only that, but certain queries take a *very* long time; the lag while typing in the rule editor is very noticeable.
The new grammar I wrote that lives in the `tree-sitter-grammars` org parses Kotlin more correctly and is easier to query since the parse tree is simpler. It also removes the noticeable lag when editing with the old Kotlin grammar, and is also an actively maintained grammar with support from tree-sitter & neovim contributors.
Kotlin supports block comments, so I moved the match arm in `get_lines_to_ignore` to be with JS/TS which checks for two slashes and a slash + asterisk, instead of just two slashes.

[STAL-2736] feat!: switch upstream Kotlin parser

---

.github/workflows/integration-tests.yaml
misc/integration-test-r.sh
misc/integration-test-rust.sh
misc/integration-test-sql.sh

We've added support for several new languages in the analyzer, but we haven't added proper end-to-end testing to ensure that we can write rules in the rule editor for these languages, retrieve them from the backend, run them in the analyzer, and get some number of results back.
This PR adds 3 integration test files, named `integration-test-{lang}.sh` which incorporate the same logic as the other currently existing integration scripts. It downloads a repository that is a project written mostly in the target language, writes a config file to use the `{lang}-inclusive` and `{lang}-code-style` rulesets in the cloned path, and executes the analyzer in this path. Each language has a `function-name-min-length` and `comments` rule which are in the `code-style` and `inclusive` rulesets for each …

[STAL-2820] feat: add end-to-end testing for R, Rust, and SQL

---

misc/integration-test-docker.sh
misc/integration-test-js-ts.sh
misc/integration-test-python.sh

As mentioned earlier, rules are subject to constant updates and changes to mitigate false positives or improve performance. Our current integration scripts check for an *exact* number of violations to be flagged, which is really brittle, as changing one rule can change this number easily if the change is mitigating false positives.
We should only check that a bare minimum number of results are detected. For example, if we're detecting around ~20, we can safely assume that we will *always* have at least 2 results. This logic was implemented in #505 with the addition of new integration tests, but we should also update the existing ones to follow this logic.
The integration scripts for python, docker, and js-ts were all updated to check for a bare minimum of 2 violations, instead of the …

chore(integration-tests): require minimum results to be at least 2

---

rust-toolchain.toml

Currently, we do not pin the Rust toolchain to a specific version when building and deploying the analyzer. This is not ideal since we'd like our builds to be reproducible across different machines that might have different default toolchain versions set.
Adding a [`rust-toolchain.toml`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file will allow us to pin the version used to build the analyzer, meaning that no matter what machine or OS version we build it on, it will always use this version.

[STAL-2577] feat: pin rust toolchain to 1.80.1

---

LICENSE-3rdparty.csv
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/file_utils.rs
crates/cli/src/sarif/sarif_utils.rs
crates/secrets/Cargo.toml
crates/secrets/src/model/secret_result.rs
crates/secrets/src/scanner.rs
misc/integration-test-secrets.sh

1. Validate the secrets
2. Show the validation status in SARIF
1. Run the validation when we find matches
2. Export the validation status in SARIF using a property
3. Adapt the severity of the rule based on the validation status
In order to export the validation status in SARIF, we introduce a struct called `SarifViolation`. The goal is to avoid introducing any secret-specific data in the `static-analysis-kernel` crate and keep it agnostic of the secret aspects.

[STAL-2964] Validate and export validation status in SARIF

---

crates/cli/src/file_utils.rs

Support `.cjs` and `.mjs` file extensions.
Add support for the extensions and treat these files as JavaScript files.
Closes #529

Add support for mjs/cjs extensions

---

crates/cli/Cargo.toml
crates/static-analysis-kernel/build.rs

While trying to compile the project in my Windows 11 machine I found out I was unable to compile the project due to some issues:
1. use of unix commands in build.rs
1. walkdir dependency mismatch
1. I replaced the UNIX commands for Rust commands.
1. Updated Walkdir to 2.5.0, which is the latest version. For some reason, the version we had in Cargo.toml (2.3.3) didn't have the `follow_root_links` method that we're using in `file_utils.rs`. Not sure how, in Mac we're getting the right version (maybe through another dependency), but this is not true in Windows, so I decided to update the dependency.
Tested this in a Windows 11 machine and it works.
RE #541

fix(windows): allow to compile in a windows machine

---

.vscode/launch.json
crates/bins/Cargo.toml
crates/bins/src/bin/datadog_static_analyzer_server/cli.rs
crates/bins/src/bin/datadog_static_analyzer_server/fairings.rs
crates/bins/src/bin/datadog_static_analyzer_server/mod.rs

We have been observing several issues when using the server in the IDE:
- intelliJ reports having multiple instances of the server that won't be automatically shutdown
- a user in VS Code reported a case where multiple processes where present at the same time after leaving his computer idle all the night (unable to reproduce on our side)
In order to better understand what's going on it would be nice to have the generated logs of the server saved into a file.
This PR adds a new option in the CLI to roll all the logs to a file. The user can decide the cadence: minutely, hourly or daily. These logs will be using JSON format for easy parsing.
These logs are saved into the `/tmp` folder in UNIX and will default to the `TEMP` env var in windows, which is usually pointing to …

feat(server): add option to save logs to a file

---

misc/github-action.sh

Remove `env` and `service` from our GitHub action and hardcode it.
Hardcode values to `datadog-static-analyzer` for the service and `ci` for the env.
Should be merged before [this PR](https://github.com/DataDog/datadog-static-analyzer-github-action/pull/47).

[STAL-3099] Remove env and service

---

.gitlab-ci.yml

Containerization has been an industry standard for many years now, but many of the build tools we use have no awareness of it, and instead set defaults for concurrent processing based on the CPU count of the container host, causing failures in CI.
[Dedicated Cores for CI jobs by default](https://docs.google.com/document/d/1YKCRHk2hcs7iaheQF6ZHxzJz9VE4sXbBEuGr9IlGZno/edit?tab=t.0#heading=h.k4f2rhz10zak) will grant the job consistent CPU resources. Which results in increased reliability and predictability.
The values were chosen based on our [diagnostic and sizing dashboard](https://app.datadoghq.com/dashboard/xff-wqx-4a2/ci-reliability-kubernetes-runner-sizing-and-diagnotic?fromUser=false&refresh_mode=sliding&tpl_var_container_name%5B0%5D=build&tpl_var_job_name%5B0%5D=test-and-build-arm64&t …

ci: enable static CPUs for build and test job

---

Cargo.toml
crates/bins/src/bin/datadog-static-analyzer-git-hook.rs
crates/bins/src/bin/datadog-static-analyzer-test-ruleset.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/common/src/analysis_options.rs
crates/static-analysis-kernel/Cargo.toml
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/bridge/query_match.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/common.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/context/file_go.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/context/file_js.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/context/file_tf.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/context/root.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/js/ts_node.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/runtime.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-server/src/request.rs

Currently, we have no way to halt the analyzer during tree-sitter query execution. This is problematic because a customer or internal user could write a rule that has a query that is very slow (suffers from combinatorial explosion).
Upgrading to tree-sitter `0.24` allows us to set a timeout on query execution. This upgrade does bring in some other breaking changes that we have to adapt, including using `streaming-iterator` to iterate over the query cursor's matches or captures, which avoids UB upstream since the iterators are stateful. Another change with the upgrade is that `Node::child_containing_descendant` was deprecated in favor of `Node::child_with_descendant`, which is almost the same, except that it can return the `self` node. So, we add a check in the loop to ensure we don't …

[STAL-2846] feat: add a timeout flag, and use it in the rule execution

---

crates/bins/src/bin/datadog-static-analyzer-git-hook.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/datadog_utils.rs
crates/cli/src/model/cli_configuration.rs
crates/cli/src/model/datadog_api.rs
crates/cli/src/sarif/sarif_utils.rs
crates/secrets/Cargo.toml
crates/secrets/src/lib.rs
crates/secrets/src/model/secret_result.rs
crates/secrets/src/model/secret_rule.rs
crates/secrets/src/scanner.rs
misc/integration-test-secrets.sh

We want to validate secrets
1. Support new secret rules formats with validation
2. Build SDS rules with validation
Add unit. and integration test with validation (test only unvalidated secrets)
```
Configuration
=============
version                : 0.4.5
revision               : development
config method          : remote configuration
cores available        : 10
cores used             : 8
#static analysis rules : 58
#secrets rules loaded  : 21
source directory       : /var/folders/8v/d16566g17b91b7zq6t5wwp000000gn/T/tmp.qTPdPIU5sI/
subdirectories         :
output file            : /tmp/bahar.json
secrets enabled        : true
output format          : sarif
ignore paths           : **/node_modules/**/*,**/jspm_packages/**/*,**/.next/**/*,**/.vuepress/**/*,**/venv/**/*,**/__pycache__/**/* …
```

[STAL-3020] Support validation

---

LICENSE-3rdparty.csv

We added a new dependency in #555, but did not add the license information for it
Add the license information for streaming-iterator

docs: add license info for `streaming-iterator`

---

crates/cli/src/datadog_utils.rs

Ensure we use the datadog backend, even when specifying a JWT.
Check for a JWT in the env variables

Ensure we use datadog backend when using a JWT

---

crates/bins/src/bin/datadog-static-analyzer-git-hook.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/constants.rs
misc/integration-git-hooks.sh

We want to distinguish each error case so that we can surface in the datadog UI why a run failed.
Put a specific exit code for each failure.
- User-specific failures are more than 50
- Program failures are less than 50

Specify error code

---

rust-toolchain.toml

Currently, our CI is failing because a transitive dependency of ours requires a Rust toolchain of `1.81` or greater. See this [workflow failure](https://github.com/DataDog/datadog-static-analyzer/actions/runs/12359902668/job/34493619718?pr=579#step:4:122) for evidence. This dependency is a part of [`rust-lang/cargo`](https://github.com/rust-lang/cargo), and we can see the MSRV was bumped in [this](https://github.com/rust-lang/cargo/commit/afb938628ec4f9781fdd51ba78f4147f6091b95f) commit to 1.81. As such, we should bump our Rust toolchain to avoid this build failure
I've bumped our Rust toolchain to 1.82, which is now close to 3 weeks old, and should be future-proof for quite some time.
Some CI jobs will fail, notably, the `check regressions` jobs as those CI workflows intend to compare …

build: bump rust toolchain to 1.82

---

crates/static-analysis-kernel/src/analysis/ddsa_lib/runtime.rs
crates/static-analysis-kernel/src/analysis/ddsa_lib/test_utils.rs

In https://github.com/DataDog/datadog-static-analyzer/pull/555 we added support for timing out tree-sitter query executions, as this was necessary to prevent the analyzing spinning forever in case a query suffered from combinatorial explosion. However, with that change, the test added to verify this actually works used the `shorthand_execute_rule_internal` function, when it should have used `shorthand_execute_rule` instead because the former does *not* test the production code path, so any changes to `JsRuntime::execute_rule` that affect the query timeout will not be caught by the test, unless the corresponding internal function is updated as well.
Instead of using `shorthand_execute_rule_internal`, we should be using `shorthand_execute_rule` to test the production code path, which this …

[K9VULN-1925] fix: improve unsound test by testing the production code path

---

crates/static-analysis-kernel/build.rs

Writing rules for the Kotlin grammar is a little more tedious than it could be, as when I was writing a rule I noticed there is a simple update to make the experience a little better. Consider the current parse tree for the given Kotlin code:
Every statement in the parse tree has a visible `statement` node as its parent, and so querying the actual node inside these statement nodes requires an unnecessary level of nesting. Ideally, the `statement` node should be a [supertype](https://tree-sitter.github.io/tree-sitter/using-parsers/6-static-node-types.html#supertype-nodes) node, similar to how the Java grammar does it [here](https://github.com/tree-sitter/tree-sitter-java/blob/94703d5a6bed02b98e438d7cad1136c01a60ba2c/grammar.js#L59).
I've updated the upstream Kotlin grammar to mark the …

[K9VULN-1928] feat: bump tree-sitter Kotlin grammar

---

crates/static-analysis-kernel/src/analysis/analyze.rs

We do have customers who want to specify the `no-dd-sa` in block comments.
For example, code such as
```
def line_with_violation(bla):
pass
```
The `no-dd-sa` should then mute violation for line `def line_with_violation(bla):`
This happens especially when customers are running multiple linters (e.g. eslint) and ignore also eslint findings. For example, in the following case, we want to disable the violation for `doSomethingThatTriggerAViolation();`
```
// no-dd-sa
// eslint-disable-next-line
doSomethingThatTriggerAViolation();
```
We see if the `no-dd-sa` directive is in a comment block. When we find a `no-dd-sa` comment, we check is there was comments below and if yes, ignore the next line until it's not a comment.

Handle `no-dd-sa` with comment blocks

---

.github/workflows/docker-build.yml
.github/workflows/release.yml

This is a follow-up PR to #600, where we noticed that our Docker container could be failing to build, and CI would not let us know of this failure. Currently, the only time we build the Docker container is when we trigger a release workflow, and not during any commit push or PR, which is not ideal. This should be tested in CI
I've added a workflow that runs on commit pushes and PRs that builds the Docker container, and verifies the binaries can be executed. The workflow is simple, and involves four steps:
- Check out the repository code
- Set up Rust
- Build the Docker container with the tag "test-image"
- Run this container 3 times one for each of our binaries (`datadog-static-analyzer`, `datadog-static-analyzer-server`, and `datadog-static-analyzer-git-hook`)
Additionally, our release …

[K9VULN-2634] ci: test that the Docker container can actually be built and run

---

crates/bins/src/bin/datadog_static_analyzer_server/cli.rs
crates/bins/src/bin/datadog_static_analyzer_server/fairings.rs
crates/bins/src/bin/datadog_static_analyzer_server/ide/Makefile.toml
crates/bins/src/bin/datadog_static_analyzer_server/state.rs
crates/static-analysis-server/src/constants.rs

All the responses from the static analysis server include some custom headers with the state of the server (i.e. whether it was initialised with a `keep-alive`, with the ability to auto shutdown...). 
`rule-timeout` and `rule-cache` where missing.
Added the missing custom headers:
IDE-4042

feat(cli): add cache and timeout information to custom headers

---

.github/workflows/ghcr.yml

With our latest release (0.5.4), publishing to GH succeeded, but building the Docker container to publish it to GHCR [failed](https://github.com/DataDog/datadog-static-analyzer/actions/runs/13012485515/job/36294483506). The runner is randomly segfaulting, and it appears to be an [upstream issue](https://github.com/tonistiigi/binfmt/issues/215) in `binfmt`, which the Docker setup QEMU action uses. 
In the linked issue, the comment [here](https://github.com/tonistiigi/binfmt/issues/215#issuecomment-2613004741) suggests that this is an issue with Ubuntu, and so, downgrading the Ubuntu version should fix our GHCR workflow from segfaulting randomly.
In the `GHCR` workflow, I've set the runner to `ubuntu-22.04` instead of `ubuntu-latest`, which fixes the segfaulting. A successful run can be …

[K9VULN-3202] ci(ghcr): downgrade the runner OS to ubuntu-22.04

---

crates/bins/src/bin/datadog_static_analyzer_server/cli.rs
crates/bins/src/bin/datadog_static_analyzer_server/mod.rs

When the static analyzer finishes with an error, from the IDE plugins we want to report the error logs to Datadog. 
- Send warning and error logs to `stderr` and the rest to `stdout`, so we can read `stderr` only from the IDE.
- Still print to the standard output even when logging to a file is enabled. Earlier, if logging to a file was enabled we would not log anything to the standard output. Note that logging to a file is still done in JSON format like earlier.
I'm not sure whether the stderr/stdout writers can actually block and need the `non_blocking` wrapper (like the file writer does). I saw some open source projects wrapping them, so I also did it just in case. This means we can now have more than one guard.

Split logs in stdout and stderr & also write there when logging to file

---

misc/github-action.sh

We want to add a flag to let the user enable or disable static analysis via environment variable. This will let the GitHub action disable static analysis if a user wants to only use secrets
Follow the same pattern as secrets except that static analysis is enabled by default. The value has to be explicitely set to false to fail.
[PR for the GItHub action](https://github.com/DataDog/datadog-static-analyzer-github-action/pull/50) to inject this variable

Add flag to disable static analysis

---

.github/workflows/ghcr.yml

Our latest release of the analyzer had a failing GHCR workflow, because of some upstream issues with Ubuntu and binfmt (which the Docker setup-qemu-action uses). For reference, see this issue - https://github.com/tonistiigi/binfmt/issues/240
As others have mentioned in the linked issue, pinning the`binfmt` image to v7.0.0-28 fixes the intermittent segfaults, and it does for us as well. In my fork, I've done a full run of the release workflow to verify that pinning the image works - [job summary](https://github.com/amaanq/datadog-static-analyzer/actions/runs/13332618563/job/37241206613)

ci(ghcr): pin binfmt to v7.0.0-28

---

Cargo.lock
Cargo.toml
crates/secrets/src/scanner.rs
versions.json

Today, the message reported in the SARIF format is the description of the rule. We should put the name of the rule to avoid very large message like the following.
Put the name of the rule in the SARIF results.
Tested in staging, result
```
{
"fixes": [],
"level": "none",
"locations": [
{
"physicalLocation": {
"artifactLocation": {
"uri": "plop.js"
},
"region": {
"endColumn": 58,
"endLine": 6,
"startColumn": 18,
"startLine": 6
}
}
}
],
"message": {
"text": "Github Access Token Scanner"
},
"partialFingerprints": {
"DATADOG_FINGERPRINT": "049bd4ae32bcbe59949e2dec09eb7d8ab1185b753056ab10dc2dc200ab7ef32d"
},
"properties": {
"tags": [
"DATADOG_CATEGORY:SECURITY",
"DATADOG_SECRET_VALIDATION_STATUS:INVALID"
]
},
"ruleId": "secrets/github-access-token",
"ruleIndex": 900
},
```

Change message in SARIF results

---

.github/workflows/integration-tests.yaml
crates/bins/src/bin/datadog-static-analyzer.rs
crates/bins/src/lib.rs
crates/cli/src/file_utils.rs
misc/integration-test-encoding.sh
misc/integration-test-secrets.sh

We want to be able to scan files with encoding different than UTF-8
Change the functions to read files so that
- we try to read UTF-8 first
- if we fail, we fallback and convert the invalid UTF-8 characters into artifacts
Added integration tests with the `sast-files-encoding` [repository](https://github.com/muh-nee/sast-files-encoding) that exposes data with different encodings.

Handle invalid UTF-8 characters

---

.github/workflows/ghcr.yml

Our GHCR workflow is failing for the latest release, see [here](https://github.com/DataDog/datadog-static-analyzer/actions/runs/14317017350/job/40126453574)
Removing the pinning of the image works, which means we're using QEMU v9 for ARM emulation.
This PR reverts the following PRs that downgraded the runner and pinned QEMU to v7:
- https://github.com/DataDog/datadog-static-analyzer/pull/618
- https://github.com/DataDog/datadog-static-analyzer/pull/643
A successful run of this build can be observed in my fork [here](https://github.com/amaanq/datadog-static-analyzer/actions/runs/14408677579/job/40412273588)
I bumped to Ubuntu latest because that, along with the unpinning, had succeeded in my fork. Ideally, we should be on the latest stable release of Ubuntu, but we had to downgrade to fix …

[K9VULN-4521] ci(ghcr): fix broken build by unpinning qemu

---

Cargo.lock
crates/cli/src/model/datadog_api.rs
crates/cli/src/sarif/sarif_utils.rs
crates/secrets/Cargo.toml
crates/secrets/src/model/secret_rule.rs
crates/secrets/src/scanner.rs

The next time the SCA team tries to bump the dd-sds lib, they will have a hard time understanding breaking changes.
I prefer bumping the lib myself, as I know how to solve the breaking changes.

[SDS-1024] Bump dd-sds in datadog-static-analyzer

---

Cargo.lock
crates/secrets/Cargo.toml

Bug in existing `dd-sds` version
Updating the `dd-sds` lib version with a [bugfix](https://github.com/DataDog/dd-sensitive-data-scanner/pull/177)
Not updating the version (not good)
The bug removed matches from the returned list of matches after calling `.validate_matches`, if there was no match validator assigned. Now, all matches are returned and the status is set to `NotAvailable` if a match validator was not available. This is an existing status so it shouldn't require any additional code changes.

bump SDS version

---

crates/bins/src/bin/datadog-static-analyzer-git-hook.rs
crates/cli/src/git_utils.rs
crates/cli/src/model/cli_configuration.rs

The original code creates undesired .git directories when trying to analyze non-git-repo directories.

Open repositories instead of initializing them

---

crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs

We want to upgrade the swift grammar of the analyzer.
Since the `parser.c` is not available in the official repo (see [this link](https://github.com/alex-pinkus/tree-sitter-swift?tab=readme-ov-file#where-is-your-parserc)), we forked the repo [here](https://github.com/muh-nee/tree-sitter-swift) and ran `tree-sitter generate` to generate the `parser.c` and `scanner.c`
I tried to use the rust package but the ABI of tree-sitter mismatched and was not working.

[K9VULN-7909] Update swift grammar
