DataDog/datadog-static-analyzer

.gitlab-ci.yml

Enable gitlab-ci

---

.gitlab-ci.yml

Bumping internal release version

Bump internal release version

---

.github/workflows/rust.yaml
README.md

1. Put more accurate information in `README.md`
2. Add tests in the CI/CD pipeline for important rulesets

Add more test and documentation

---

README.md

Fix broken links on the `README.md` file.

Fix links on the README.md

---

server/src/model/analysis_request.rs

Removes a not needed rename for the AnalysisRequest model.

chore(serde): no needed rename

---

.github/workflows/rust.yaml
bins/src/bin/datadog-static-analyzer.rs
cli/src/file_utils.rs
kernel/src/analysis/javascript.rs

Same problem than [this PR](https://github.com/DataDog/datadog-static-analyzer/pull/13) but without a barrier. The real problem is that we added more complexity rather than doing the correct fix.
In the fix in [this PR](https://github.com/DataDog/datadog-static-analyzer/pull/13), we add a barrier to synchronize the threads. The real issue is that the created thread was [notifying the condition variable](https://github.com/DataDog/datadog-static-analyzer/blob/ffce75f6a1c387b7a0e6f27089eb4463b3febb37/kernel/src/analysis/javascript.rs#L213) before the main thread could [wait on it](https://github.com/DataDog/datadog-static-analyzer/blob/ffce75f6a1c387b7a0e6f27089eb4463b3febb37/kernel/src/analysis/javascript.rs#L226). The fix added a barrier but the real issue is that the mutex of the …

Timeout fix wihout barrier

---

Cargo.toml
kernel/build.rs
kernel/src/analysis/analyze.rs
kernel/src/analysis/javascript.rs
kernel/src/analysis/tree_sitter.rs
kernel/src/model/common.rs
kernel/src/model/rule.rs
kernel/src/model/violation.rs

There are some changes that could be done to improve readability in the code, avoid allocations or simplify the code.
By following some of the Clippy recommendations I decided to apply some refactors to the codebase. I'll try to explain the rationale of each change in the code itself by leaving some messages as a mode of auto-review.
No problem if some change is deemed as subjective and you prefer to dismiss it.

chore(clippy): apply idiomatic changes

---

bins/src/bin/datadog-static-analyzer.rs

We want to show the number of violations found after executing the tool.
Show the number of violations after execution of all rules

print the number of violations before exiting

---

kernel/build.rs
kernel/src/analysis/analyze.rs
kernel/src/analysis/tree_sitter.rs
kernel/src/model/common.rs

We need to add support for more languages: C#, Dockerfile, Go, Java, JSON, YAML
Add the necessary support in our build system

moar languages

---

.gitlab-ci.yml

Update the internal release version

update the internal version release

---

Cargo.toml
cli/src/sarif/sarif_utils.rs
kernel/src/model/rule.rs
versions.json

We want to add a short description to the SARIF export for each rule.
Add the short description to the rule when it's specified.
We bumped the version in preparation for a new release.

add short description to the rule

---

.gitlab-ci.yml

updated internal version

---

.github/CODEOWNERS

Adding clarity on the code owners for the project.

add CODEOWNERS for stella

---

bins/src/bin/datadog-static-analyzer.rs

Removing useless `print` statements

remove print statement

---

README.md

Small typo in the readme
Corrected the typo

docs(readme): fix small typo

---

.gitlab-ci.yml
Cargo.toml
versions.json

prepare version 0.0.7

---

.gitlab-ci.yml
README.md

Add options that were not documented

Add undocumented options

---

Cargo.toml
versions.json

Bump version for a new release of the tool.

Prepare version 0.0.8

---

.gitlab-ci.yml

It's not possible to take the service account of another repository

Update IAM permission CI

---

bins/src/bin/datadog-static-analyzer-server.rs

We want to have a specific option to the server binary to specify a port
Add an option `--port` to the server so that we can specify the server port.
```
$ cargo run --bin datadog-static-analyzer-server
🚀 Rocket has launched from http://127.0.0.1:8000
```
```
$ cargo run --bin datadog-static-analyzer-server -- --port 9000
🚀 Rocket has launched from http://127.0.0.1:9000
```
```
cargo run --bin datadog-static-analyzer-server -- --port weoihj                                                                                                                                                                                
Invalid port argument
```

Add option to specify server port

---

bins/src/bin/datadog-static-analyzer.rs

remove debug line

---

Cargo.toml
versions.json

Bump version number for new release

Prepare versoin 0.1.1

---

LICENSE-3rdparty.csv
bins/Cargo.toml
bins/src/bin/datadog-static-analyzer-server.rs
cli/Cargo.toml
cli/src/sarif/sarif_utils.rs
kernel/Cargo.toml

We want to add the capability to exit the server if there was no `/ping` request for a given period of time.
Introduce an option `-k` for the server. The `-k` option takes a parameter that is a number of seconds. If there is no ping response during this number of seconds, the server exits.

Add mechanism to exit the server after no request

---

.gitlab-ci.yml
Cargo.toml
versions.json

Prepare release 0.1.2

---

.github/workflows/integration-tests.yaml

Simplify GitHub action script and avoid heavy copy/paste

simplify github action invocation

---

.github/workflows/integration-tests.yaml

Disable `docker-best-practices` in the CI pipeline.

Disable test suite with docker-best-practices

---

cli/src/file_utils.rs
kernel/Cargo.toml
kernel/build.rs
kernel/src/analysis/analyze.rs
kernel/src/analysis/tree_sitter.rs
kernel/src/model/common.rs

We want to make sure we can support Kotlin and Swift.
1. Adding support for the language
2. Add test to make sure the languages parse
The Swift grammar does not build out of the box. We need to use the rust package instead of using the sources.

Support Kotlin and Swift

---

.github/workflows/integration-tests.yaml
.github/workflows/production-rules.yaml
.github/workflows/rust.yaml

Checks are not working in CI/CD for a pull request
Add them for a pull request

Add CI/CD for Pull Request

---

.github/workflows/production-rules.yaml
.gitlab-ci.yml

Also perform integration tests in gitlab. The integration tests do not pass for `AMD64`, this will be fixed later

Integration tests in gitlab

---

DEVELOPMENT.md

Add instructions to start a server

Add server start instructions

---

.gitlab-ci.yml
LICENSE-3rdparty.csv
bins/Cargo.toml
kernel/Cargo.toml
kernel/build.rs
kernel/src/analysis/analyze.rs
kernel/src/analysis/javascript.rs

Bring back the server in a stable situation
Rollback recent changes that may have introduce some stability issue.

[STAL-980] Attempt to fix issues, going back to previous versions

---

.github/workflows/sca.yml

Generating SBOM for each subproject so that dependencies are detected.
Generate the SBOM using `cargo`
Dependencies are found then.

Fix dependencies scanning

---

Cargo.toml
versions.json

Add version 0.2.5

---

Cargo.toml
versions.json

Prepare 0.2.6

---

crates/cli/src/file_utils.rs
crates/cli/src/model/config_file.rs

Make the matcher function a member of PathPattern.

---

LICENSE-3rdparty.csv
crates/cli/Cargo.toml
crates/cli/src/csv.rs

Customers complain that the CSV output is incorrect because it does not escape characters as it should be. The CSV is built manually today using our string concatenation.
Use a library which handles CSV files properly. This way, characters are being properly escaped.

[STAL-1486] Properly handle CSV output

---

FAQ.md
README.md

Document that we do not support Alpine and how to use CSV files as well as how to make the CLI exit when a violation is present.

[STAL-1470] add details in FAQ

---

.gitlab-ci.yml

Check all ruby rules in production in our Gitlab pipeline.

check ruby rules in gitlab pipeline

---

README.md

The links use `http` when they should use `https`
Update the links
Leave as is.
n/a

Update links to https

---

README.md

The new configuration options for ignore/only and rulesets and rules are not documented yet.

Update README.md with ignore/only and ruleset/rule config information.

---

README.md
RULESETS.md
crates/cli/src/datadog_utils.rs

There is no documentation for diff-aware scanning.
Add documentation for diff-aware scanning.
Also updated the list of rules available.

[STAL-1523] add documentation for diff-aware

---

doc/diff-aware.md

Add documentation for diff-aware
Add a file diff-aware.md that explains how the feature works and what are the main potential issues
[result](https://github.com/DataDog/datadog-static-analyzer/blob/juli1/STAL-1523-part2/doc/diff-aware.md)

[STAL-1523] add diff-aware doc

---

.github/workflows/production-rules.yaml
RULESETS.md

I noticed that we were missing rulesets in the documentation and production rule integration tests.
Add the missing rulesets.
Leave the docs outdated 👎

[STAL] Add missing rulesets

---

crates/cli/src/model/cli_configuration.rs
crates/cli/src/model/datadog_api.rs
crates/cli/src/rule_utils.rs
crates/cli/src/sarif/sarif_utils.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/javascript.rs
crates/static-analysis-kernel/src/model/rule.rs
crates/static-analysis-server/src/model/analysis_request.rs
crates/static-analysis-server/src/request.rs

The 'variables' field is not used. The 'arguments' field, however, is new and is to be used.
Remove 'variables', add 'arguments'.

Read the 'arguments' field from the rules

---

README.md

Rule arguments are undocumented.
Document rule arguments.
Not documenting rule arguments.
Wording still seems a little awkward to me. Suggestions more than welcome.

Document the ability to set rule arguments.

---

crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/endpoints.rs

It's not a problem per se, but we thought it would be better to return raw strings instead of using JSON strings.
Changed the affected endpoints to return a raw string.
IDE-2626

feat(ide): return raw string instead of JSON

---

crates/bins/src/bin/datadog_static_analyzer_server/ide/configuration_file/static_analysis_config_file.rs

When globally ignoring a rule, the rule was completely overriden. As we have to support new properties we must keep them even if the rule is ignored.
Properly handle this case and keep the existing properties. So basically, mutate the `paths.ignore` property if the rule was already present.
re #301
IDE-2627

fix(ide): support for new properties when ignoring rules

---

crates/cli/src/sarif/sarif_utils.rs

Add the version of the tool in the SARIF report
Add the version in the `version` field of the tool section.

Add version of the tool

---

FAQ.md
README.md
doc/report-issue.md

Documenting how to report an error
Add documentation

Add documentation on reporting issue

---

Cargo.toml
versions.json

Prepare new version to add new performance switches

Prepare version 0.3.1

---

Cargo.toml
versions.json

Prepare version 0.3.2, bumping versions.

Prepare version 0.3.2

---

misc/test-production-rules.py

Users do not have clear instructions to test production rules.
Add the documentation to run the script locally

[STAL-2002] Add documentation

---

Cargo.toml
versions.json

Preparing 0.3.3 to expose handling for rules marked as `is_testing`

Preparing 0.3.3

---

doc/owasp-benchmark.md

Fix instructions to reproduce the OWASP benchmark
Update according to solution from #351 
Closes: #351

Fix OWASP benchmark changes

---

crates/static-analysis-kernel/Cargo.toml

Update tree-sitter to latest version

Test tree-sitter 0.22.6

---

.github/workflows/test-rules.yaml

simple wording fix, confused me for a sec when CI ran

fix: correct workflow step name for staging rules

---

.github/workflows/test-rules.yaml
.gitlab-ci.yml
misc/test-rules.py

Today, we test rulesets by name whereas we should test all the default rulesets for a language
Update the script `test-rules.py` to take a language as argument. We then fetch the default rulesets for the language and test each of them.

Test all default rulesets

---

misc/test-rules.py

Currently, our CI script `test-rules.py` does not have a retry mechanism in every spot where making a request could fail. This can cause a whole CI job/pipeline to fail, but it could be a case where making a second requests succeeds, for whatever reason (flakiness from GH or the api, or wherever else). This is not ideal and we should have a retry mechanism that tries a few times before giving up.
Add a loop that retries 5 times before exiting with an error. If we get 5 erroneous responses back, then we can be sure that this is not failing due to flakiness and something is likely down or broken. I've also taken the liberty to fix a few other potential spots for bugs and improved the script with better error handling in some spots. 
For example, we check if an environment variable exists by …

[STAL-2296] fix: improve `test-rules` script with retries and better error handling

---

README.md
doc/docker-container.md

We do not have any documentation on how to use our Docker container
Add docs

[STAL-2379] docs: document how to use the Docker container

---

crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/sarif/sarif_utils.rs

The SARIF rule from SDS do not have a short description
Add the short description

[secrets] add short description

---

crates/bins/src/bin/datadog-static-analyzer.rs

The total execution time given by `--performance-statistics` varies wildly between repos, as it adds up all the time for all files. This is not very useful to keep track of the average execution time.
Display the number of files alongside each rule's execution time. This lets us compute an average.

Display the number of files with each rule's execution time.

---

.github/workflows/integration-tests.yaml
crates/bins/src/bin/datadog-static-analyzer-git-hooks.rs
misc/integration-git-hooks.sh

Have an integration test to ensure hooks work as expected
Have a test that create a new repo, add a secret in a new branch and ensure it's detected

add integration testing for secrets

---

LICENSE-3rdparty.csv
crates/bins/Cargo.toml
crates/bins/src/bin/datadog-static-analyzer-git-hook.rs

The recently introduced `console` library causes issues with the buiid.
Switching to a lightweight library.

switch library emoji

---

misc/github-action.sh

We want to introduce an option to enable secrets in the GitHub action
Add a new option to enabled secrets

Prepare github action script for secrets

---

Cargo.toml
versions.json

Prepare version 0.3.9

---

crates/bins/src/bin/datadog-static-analyzer-git-hook.rs
crates/bins/src/bin/datadog-static-analyzer.rs
crates/cli/src/sarif/sarif_utils.rs
misc/integration-git-hooks.sh

For statistics purposes, we want to export the results of the Git hook.
Export all the results in a file with the `--output` parameter.

Add results when running a Git Hook

---

misc/integration-test-js-ts.sh

Making our test suite stronger
Checking we catch violations at each commit/push

Add tests for JS/TS

---

Cargo.toml
versions.json

Prepare version 0.4.2

---

Cargo.toml
versions.json

Release new version to 0.4.6 to update the Github action script in the container.

Update version 0.4.6

---

crates/bins/src/bin/datadog_static_analyzer_server/cli.rs
crates/bins/src/bin/datadog_static_analyzer_server/mod.rs

IntelliJ would like to define the directory to save the logs.
Added a new option to define the path of the folder to save the logs.
IDE-3777

feat(server): add param to define logs directory

---

Cargo.toml
versions.json

Prepare version 0.4.8

---

crates/cli/src/file_utils.rs
crates/static-analysis-kernel/Cargo.toml
crates/static-analysis-kernel/build.rs
crates/static-analysis-kernel/src/analysis/analyze.rs
crates/static-analysis-kernel/src/analysis/tree_sitter.rs
crates/static-analysis-kernel/src/model/common.rs

Add Elixir support
Add the [tree-sitter grammar](https://github.com/elixir-lang/tree-sitter-elixir/tree/main) from the `elixir-lang` GitHub account.
Added unit tests to ensure parsing works correctly.

[K9VULN-2580] Add Elixir support

---

Cargo.toml
versions.json

New version with elixir support + ignore multi-lines

Release Version 0.5.3

---

Cargo.toml
versions.json

Release 0.5.5

---

Cargo.lock
Cargo.toml
versions.json

Prepare version 0.5.6

---

Cargo.lock
Cargo.toml
crates/secrets/Cargo.toml
versions.json

Update the SDS library and [integrate a bugfix](https://github.com/DataDog/dd-sensitive-data-scanner/pull/159) that occurred in our scanner
Update SDS + prepare a new release

Update SDS version

---

crates/static-analysis-kernel/build.rs

update swift grammar
use the latest artifact from the branch `with-generated-files` from the [tree-sitter-swift ](https://github.com/alex-pinkus/tree-sitter-swift/tree/with-generated-files)project

update swift grammar

---

Cargo.lock
Cargo.toml
versions.json

Release a new version/revision of the analyzer

Release version 0.6.2

---

Cargo.lock
Cargo.toml
versions.json

Version 0.6.5

---

Cargo.lock
Cargo.toml
versions.json

Update version to 0.6.8

---

crates/static-analysis-kernel/src/analysis/ddsa_lib/js/ddsa.js
crates/static-analysis-kernel/src/analysis/ddsa_lib/js/ddsa.rs

Adding new helper function in the DDSA runtime
Adding the functions `getParentWithCondition` and `getChildWithCondition` that returns nodes that satisfies a given condition.

[K9VULN-8052] Add new helper functions

---

Dockerfile

Issues with outdated certificates as shown in #759 
Update the build and docker file
Fixes #759

[K9VULN-8113] Fix Dockerfile and avoid outdated certificates
